# coding: utf-8

"""
    rds_mysql_v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class CreateDBBlueGreenInstanceRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'charge_info': 'ChargeInfoForCreateDBBlueGreenInstanceInput',
        'db_engine_version': 'str',
        'db_param_group_id': 'str',
        'deletion_protection': 'str',
        'instance_id': 'str',
        'instance_name': 'str',
        'instance_type': 'str',
        'minor_version': 'str',
        'node_info': 'list[NodeInfoForCreateDBBlueGreenInstanceInput]',
        'private_ip_address': 'str',
        'proxy_node_custom': 'ProxyNodeCustomForCreateDBBlueGreenInstanceInput',
        'storage_space': 'int',
        'storage_type': 'str',
        'subnet_id': 'str'
    }

    attribute_map = {
        'charge_info': 'ChargeInfo',
        'db_engine_version': 'DBEngineVersion',
        'db_param_group_id': 'DBParamGroupId',
        'deletion_protection': 'DeletionProtection',
        'instance_id': 'InstanceId',
        'instance_name': 'InstanceName',
        'instance_type': 'InstanceType',
        'minor_version': 'MinorVersion',
        'node_info': 'NodeInfo',
        'private_ip_address': 'PrivateIpAddress',
        'proxy_node_custom': 'ProxyNodeCustom',
        'storage_space': 'StorageSpace',
        'storage_type': 'StorageType',
        'subnet_id': 'SubnetId'
    }

    def __init__(self, charge_info=None, db_engine_version=None, db_param_group_id=None, deletion_protection=None, instance_id=None, instance_name=None, instance_type=None, minor_version=None, node_info=None, private_ip_address=None, proxy_node_custom=None, storage_space=None, storage_type=None, subnet_id=None, _configuration=None):  # noqa: E501
        """CreateDBBlueGreenInstanceRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._charge_info = None
        self._db_engine_version = None
        self._db_param_group_id = None
        self._deletion_protection = None
        self._instance_id = None
        self._instance_name = None
        self._instance_type = None
        self._minor_version = None
        self._node_info = None
        self._private_ip_address = None
        self._proxy_node_custom = None
        self._storage_space = None
        self._storage_type = None
        self._subnet_id = None
        self.discriminator = None

        if charge_info is not None:
            self.charge_info = charge_info
        self.db_engine_version = db_engine_version
        if db_param_group_id is not None:
            self.db_param_group_id = db_param_group_id
        if deletion_protection is not None:
            self.deletion_protection = deletion_protection
        self.instance_id = instance_id
        if instance_name is not None:
            self.instance_name = instance_name
        if instance_type is not None:
            self.instance_type = instance_type
        if minor_version is not None:
            self.minor_version = minor_version
        if node_info is not None:
            self.node_info = node_info
        if private_ip_address is not None:
            self.private_ip_address = private_ip_address
        if proxy_node_custom is not None:
            self.proxy_node_custom = proxy_node_custom
        self.storage_space = storage_space
        self.storage_type = storage_type
        if subnet_id is not None:
            self.subnet_id = subnet_id

    @property
    def charge_info(self):
        """Gets the charge_info of this CreateDBBlueGreenInstanceRequest.  # noqa: E501


        :return: The charge_info of this CreateDBBlueGreenInstanceRequest.  # noqa: E501
        :rtype: ChargeInfoForCreateDBBlueGreenInstanceInput
        """
        return self._charge_info

    @charge_info.setter
    def charge_info(self, charge_info):
        """Sets the charge_info of this CreateDBBlueGreenInstanceRequest.


        :param charge_info: The charge_info of this CreateDBBlueGreenInstanceRequest.  # noqa: E501
        :type: ChargeInfoForCreateDBBlueGreenInstanceInput
        """

        self._charge_info = charge_info

    @property
    def db_engine_version(self):
        """Gets the db_engine_version of this CreateDBBlueGreenInstanceRequest.  # noqa: E501


        :return: The db_engine_version of this CreateDBBlueGreenInstanceRequest.  # noqa: E501
        :rtype: str
        """
        return self._db_engine_version

    @db_engine_version.setter
    def db_engine_version(self, db_engine_version):
        """Sets the db_engine_version of this CreateDBBlueGreenInstanceRequest.


        :param db_engine_version: The db_engine_version of this CreateDBBlueGreenInstanceRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and db_engine_version is None:
            raise ValueError("Invalid value for `db_engine_version`, must not be `None`")  # noqa: E501

        self._db_engine_version = db_engine_version

    @property
    def db_param_group_id(self):
        """Gets the db_param_group_id of this CreateDBBlueGreenInstanceRequest.  # noqa: E501


        :return: The db_param_group_id of this CreateDBBlueGreenInstanceRequest.  # noqa: E501
        :rtype: str
        """
        return self._db_param_group_id

    @db_param_group_id.setter
    def db_param_group_id(self, db_param_group_id):
        """Sets the db_param_group_id of this CreateDBBlueGreenInstanceRequest.


        :param db_param_group_id: The db_param_group_id of this CreateDBBlueGreenInstanceRequest.  # noqa: E501
        :type: str
        """

        self._db_param_group_id = db_param_group_id

    @property
    def deletion_protection(self):
        """Gets the deletion_protection of this CreateDBBlueGreenInstanceRequest.  # noqa: E501


        :return: The deletion_protection of this CreateDBBlueGreenInstanceRequest.  # noqa: E501
        :rtype: str
        """
        return self._deletion_protection

    @deletion_protection.setter
    def deletion_protection(self, deletion_protection):
        """Sets the deletion_protection of this CreateDBBlueGreenInstanceRequest.


        :param deletion_protection: The deletion_protection of this CreateDBBlueGreenInstanceRequest.  # noqa: E501
        :type: str
        """

        self._deletion_protection = deletion_protection

    @property
    def instance_id(self):
        """Gets the instance_id of this CreateDBBlueGreenInstanceRequest.  # noqa: E501


        :return: The instance_id of this CreateDBBlueGreenInstanceRequest.  # noqa: E501
        :rtype: str
        """
        return self._instance_id

    @instance_id.setter
    def instance_id(self, instance_id):
        """Sets the instance_id of this CreateDBBlueGreenInstanceRequest.


        :param instance_id: The instance_id of this CreateDBBlueGreenInstanceRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and instance_id is None:
            raise ValueError("Invalid value for `instance_id`, must not be `None`")  # noqa: E501

        self._instance_id = instance_id

    @property
    def instance_name(self):
        """Gets the instance_name of this CreateDBBlueGreenInstanceRequest.  # noqa: E501


        :return: The instance_name of this CreateDBBlueGreenInstanceRequest.  # noqa: E501
        :rtype: str
        """
        return self._instance_name

    @instance_name.setter
    def instance_name(self, instance_name):
        """Sets the instance_name of this CreateDBBlueGreenInstanceRequest.


        :param instance_name: The instance_name of this CreateDBBlueGreenInstanceRequest.  # noqa: E501
        :type: str
        """

        self._instance_name = instance_name

    @property
    def instance_type(self):
        """Gets the instance_type of this CreateDBBlueGreenInstanceRequest.  # noqa: E501


        :return: The instance_type of this CreateDBBlueGreenInstanceRequest.  # noqa: E501
        :rtype: str
        """
        return self._instance_type

    @instance_type.setter
    def instance_type(self, instance_type):
        """Sets the instance_type of this CreateDBBlueGreenInstanceRequest.


        :param instance_type: The instance_type of this CreateDBBlueGreenInstanceRequest.  # noqa: E501
        :type: str
        """

        self._instance_type = instance_type

    @property
    def minor_version(self):
        """Gets the minor_version of this CreateDBBlueGreenInstanceRequest.  # noqa: E501


        :return: The minor_version of this CreateDBBlueGreenInstanceRequest.  # noqa: E501
        :rtype: str
        """
        return self._minor_version

    @minor_version.setter
    def minor_version(self, minor_version):
        """Sets the minor_version of this CreateDBBlueGreenInstanceRequest.


        :param minor_version: The minor_version of this CreateDBBlueGreenInstanceRequest.  # noqa: E501
        :type: str
        """

        self._minor_version = minor_version

    @property
    def node_info(self):
        """Gets the node_info of this CreateDBBlueGreenInstanceRequest.  # noqa: E501


        :return: The node_info of this CreateDBBlueGreenInstanceRequest.  # noqa: E501
        :rtype: list[NodeInfoForCreateDBBlueGreenInstanceInput]
        """
        return self._node_info

    @node_info.setter
    def node_info(self, node_info):
        """Sets the node_info of this CreateDBBlueGreenInstanceRequest.


        :param node_info: The node_info of this CreateDBBlueGreenInstanceRequest.  # noqa: E501
        :type: list[NodeInfoForCreateDBBlueGreenInstanceInput]
        """

        self._node_info = node_info

    @property
    def private_ip_address(self):
        """Gets the private_ip_address of this CreateDBBlueGreenInstanceRequest.  # noqa: E501


        :return: The private_ip_address of this CreateDBBlueGreenInstanceRequest.  # noqa: E501
        :rtype: str
        """
        return self._private_ip_address

    @private_ip_address.setter
    def private_ip_address(self, private_ip_address):
        """Sets the private_ip_address of this CreateDBBlueGreenInstanceRequest.


        :param private_ip_address: The private_ip_address of this CreateDBBlueGreenInstanceRequest.  # noqa: E501
        :type: str
        """

        self._private_ip_address = private_ip_address

    @property
    def proxy_node_custom(self):
        """Gets the proxy_node_custom of this CreateDBBlueGreenInstanceRequest.  # noqa: E501


        :return: The proxy_node_custom of this CreateDBBlueGreenInstanceRequest.  # noqa: E501
        :rtype: ProxyNodeCustomForCreateDBBlueGreenInstanceInput
        """
        return self._proxy_node_custom

    @proxy_node_custom.setter
    def proxy_node_custom(self, proxy_node_custom):
        """Sets the proxy_node_custom of this CreateDBBlueGreenInstanceRequest.


        :param proxy_node_custom: The proxy_node_custom of this CreateDBBlueGreenInstanceRequest.  # noqa: E501
        :type: ProxyNodeCustomForCreateDBBlueGreenInstanceInput
        """

        self._proxy_node_custom = proxy_node_custom

    @property
    def storage_space(self):
        """Gets the storage_space of this CreateDBBlueGreenInstanceRequest.  # noqa: E501


        :return: The storage_space of this CreateDBBlueGreenInstanceRequest.  # noqa: E501
        :rtype: int
        """
        return self._storage_space

    @storage_space.setter
    def storage_space(self, storage_space):
        """Sets the storage_space of this CreateDBBlueGreenInstanceRequest.


        :param storage_space: The storage_space of this CreateDBBlueGreenInstanceRequest.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and storage_space is None:
            raise ValueError("Invalid value for `storage_space`, must not be `None`")  # noqa: E501

        self._storage_space = storage_space

    @property
    def storage_type(self):
        """Gets the storage_type of this CreateDBBlueGreenInstanceRequest.  # noqa: E501


        :return: The storage_type of this CreateDBBlueGreenInstanceRequest.  # noqa: E501
        :rtype: str
        """
        return self._storage_type

    @storage_type.setter
    def storage_type(self, storage_type):
        """Sets the storage_type of this CreateDBBlueGreenInstanceRequest.


        :param storage_type: The storage_type of this CreateDBBlueGreenInstanceRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and storage_type is None:
            raise ValueError("Invalid value for `storage_type`, must not be `None`")  # noqa: E501

        self._storage_type = storage_type

    @property
    def subnet_id(self):
        """Gets the subnet_id of this CreateDBBlueGreenInstanceRequest.  # noqa: E501


        :return: The subnet_id of this CreateDBBlueGreenInstanceRequest.  # noqa: E501
        :rtype: str
        """
        return self._subnet_id

    @subnet_id.setter
    def subnet_id(self, subnet_id):
        """Sets the subnet_id of this CreateDBBlueGreenInstanceRequest.


        :param subnet_id: The subnet_id of this CreateDBBlueGreenInstanceRequest.  # noqa: E501
        :type: str
        """

        self._subnet_id = subnet_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateDBBlueGreenInstanceRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateDBBlueGreenInstanceRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateDBBlueGreenInstanceRequest):
            return True

        return self.to_dict() != other.to_dict()
