# coding: utf-8

"""
    cloudidentity

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class ListPermissionPoliciesInPermissionSetRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'page_number': 'int',
        'page_size': 'int',
        'permission_policy_type': 'str',
        'permission_set_id': 'str'
    }

    attribute_map = {
        'page_number': 'PageNumber',
        'page_size': 'PageSize',
        'permission_policy_type': 'PermissionPolicyType',
        'permission_set_id': 'PermissionSetId'
    }

    def __init__(self, page_number=None, page_size=None, permission_policy_type=None, permission_set_id=None, _configuration=None):  # noqa: E501
        """ListPermissionPoliciesInPermissionSetRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._page_number = None
        self._page_size = None
        self._permission_policy_type = None
        self._permission_set_id = None
        self.discriminator = None

        if page_number is not None:
            self.page_number = page_number
        if page_size is not None:
            self.page_size = page_size
        if permission_policy_type is not None:
            self.permission_policy_type = permission_policy_type
        self.permission_set_id = permission_set_id

    @property
    def page_number(self):
        """Gets the page_number of this ListPermissionPoliciesInPermissionSetRequest.  # noqa: E501


        :return: The page_number of this ListPermissionPoliciesInPermissionSetRequest.  # noqa: E501
        :rtype: int
        """
        return self._page_number

    @page_number.setter
    def page_number(self, page_number):
        """Sets the page_number of this ListPermissionPoliciesInPermissionSetRequest.


        :param page_number: The page_number of this ListPermissionPoliciesInPermissionSetRequest.  # noqa: E501
        :type: int
        """

        self._page_number = page_number

    @property
    def page_size(self):
        """Gets the page_size of this ListPermissionPoliciesInPermissionSetRequest.  # noqa: E501


        :return: The page_size of this ListPermissionPoliciesInPermissionSetRequest.  # noqa: E501
        :rtype: int
        """
        return self._page_size

    @page_size.setter
    def page_size(self, page_size):
        """Sets the page_size of this ListPermissionPoliciesInPermissionSetRequest.


        :param page_size: The page_size of this ListPermissionPoliciesInPermissionSetRequest.  # noqa: E501
        :type: int
        """

        self._page_size = page_size

    @property
    def permission_policy_type(self):
        """Gets the permission_policy_type of this ListPermissionPoliciesInPermissionSetRequest.  # noqa: E501


        :return: The permission_policy_type of this ListPermissionPoliciesInPermissionSetRequest.  # noqa: E501
        :rtype: str
        """
        return self._permission_policy_type

    @permission_policy_type.setter
    def permission_policy_type(self, permission_policy_type):
        """Sets the permission_policy_type of this ListPermissionPoliciesInPermissionSetRequest.


        :param permission_policy_type: The permission_policy_type of this ListPermissionPoliciesInPermissionSetRequest.  # noqa: E501
        :type: str
        """
        allowed_values = ["System", "Inline"]  # noqa: E501
        if (self._configuration.client_side_validation and
                permission_policy_type not in allowed_values):
            raise ValueError(
                "Invalid value for `permission_policy_type` ({0}), must be one of {1}"  # noqa: E501
                .format(permission_policy_type, allowed_values)
            )

        self._permission_policy_type = permission_policy_type

    @property
    def permission_set_id(self):
        """Gets the permission_set_id of this ListPermissionPoliciesInPermissionSetRequest.  # noqa: E501


        :return: The permission_set_id of this ListPermissionPoliciesInPermissionSetRequest.  # noqa: E501
        :rtype: str
        """
        return self._permission_set_id

    @permission_set_id.setter
    def permission_set_id(self, permission_set_id):
        """Sets the permission_set_id of this ListPermissionPoliciesInPermissionSetRequest.


        :param permission_set_id: The permission_set_id of this ListPermissionPoliciesInPermissionSetRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and permission_set_id is None:
            raise ValueError("Invalid value for `permission_set_id`, must not be `None`")  # noqa: E501

        self._permission_set_id = permission_set_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ListPermissionPoliciesInPermissionSetRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListPermissionPoliciesInPermissionSetRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ListPermissionPoliciesInPermissionSetRequest):
            return True

        return self.to_dict() != other.to_dict()
