# coding: utf-8

"""
    tidb

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class SourceForListImportTasksOutput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'azure_blob': 'AzureBlobForListImportTasksOutput',
        'gcs': 'GcsForListImportTasksOutput',
        'local': 'LocalForListImportTasksOutput',
        'oss': 'OssForListImportTasksOutput',
        's3': 'S3ForListImportTasksOutput',
        's3_compatible': 'S3CompatibleForListImportTasksOutput',
        'target_table_infos': 'list[TargetTableInfoForListImportTasksOutput]',
        'tos': 'TosForListImportTasksOutput',
        'type': 'str'
    }

    attribute_map = {
        'azure_blob': 'AzureBlob',
        'gcs': 'Gcs',
        'local': 'Local',
        'oss': 'Oss',
        's3': 'S3',
        's3_compatible': 'S3Compatible',
        'target_table_infos': 'TargetTableInfos',
        'tos': 'Tos',
        'type': 'Type'
    }

    def __init__(self, azure_blob=None, gcs=None, local=None, oss=None, s3=None, s3_compatible=None, target_table_infos=None, tos=None, type=None, _configuration=None):  # noqa: E501
        """SourceForListImportTasksOutput - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._azure_blob = None
        self._gcs = None
        self._local = None
        self._oss = None
        self._s3 = None
        self._s3_compatible = None
        self._target_table_infos = None
        self._tos = None
        self._type = None
        self.discriminator = None

        if azure_blob is not None:
            self.azure_blob = azure_blob
        if gcs is not None:
            self.gcs = gcs
        if local is not None:
            self.local = local
        if oss is not None:
            self.oss = oss
        if s3 is not None:
            self.s3 = s3
        if s3_compatible is not None:
            self.s3_compatible = s3_compatible
        if target_table_infos is not None:
            self.target_table_infos = target_table_infos
        if tos is not None:
            self.tos = tos
        if type is not None:
            self.type = type

    @property
    def azure_blob(self):
        """Gets the azure_blob of this SourceForListImportTasksOutput.  # noqa: E501


        :return: The azure_blob of this SourceForListImportTasksOutput.  # noqa: E501
        :rtype: AzureBlobForListImportTasksOutput
        """
        return self._azure_blob

    @azure_blob.setter
    def azure_blob(self, azure_blob):
        """Sets the azure_blob of this SourceForListImportTasksOutput.


        :param azure_blob: The azure_blob of this SourceForListImportTasksOutput.  # noqa: E501
        :type: AzureBlobForListImportTasksOutput
        """

        self._azure_blob = azure_blob

    @property
    def gcs(self):
        """Gets the gcs of this SourceForListImportTasksOutput.  # noqa: E501


        :return: The gcs of this SourceForListImportTasksOutput.  # noqa: E501
        :rtype: GcsForListImportTasksOutput
        """
        return self._gcs

    @gcs.setter
    def gcs(self, gcs):
        """Sets the gcs of this SourceForListImportTasksOutput.


        :param gcs: The gcs of this SourceForListImportTasksOutput.  # noqa: E501
        :type: GcsForListImportTasksOutput
        """

        self._gcs = gcs

    @property
    def local(self):
        """Gets the local of this SourceForListImportTasksOutput.  # noqa: E501


        :return: The local of this SourceForListImportTasksOutput.  # noqa: E501
        :rtype: LocalForListImportTasksOutput
        """
        return self._local

    @local.setter
    def local(self, local):
        """Sets the local of this SourceForListImportTasksOutput.


        :param local: The local of this SourceForListImportTasksOutput.  # noqa: E501
        :type: LocalForListImportTasksOutput
        """

        self._local = local

    @property
    def oss(self):
        """Gets the oss of this SourceForListImportTasksOutput.  # noqa: E501


        :return: The oss of this SourceForListImportTasksOutput.  # noqa: E501
        :rtype: OssForListImportTasksOutput
        """
        return self._oss

    @oss.setter
    def oss(self, oss):
        """Sets the oss of this SourceForListImportTasksOutput.


        :param oss: The oss of this SourceForListImportTasksOutput.  # noqa: E501
        :type: OssForListImportTasksOutput
        """

        self._oss = oss

    @property
    def s3(self):
        """Gets the s3 of this SourceForListImportTasksOutput.  # noqa: E501


        :return: The s3 of this SourceForListImportTasksOutput.  # noqa: E501
        :rtype: S3ForListImportTasksOutput
        """
        return self._s3

    @s3.setter
    def s3(self, s3):
        """Sets the s3 of this SourceForListImportTasksOutput.


        :param s3: The s3 of this SourceForListImportTasksOutput.  # noqa: E501
        :type: S3ForListImportTasksOutput
        """

        self._s3 = s3

    @property
    def s3_compatible(self):
        """Gets the s3_compatible of this SourceForListImportTasksOutput.  # noqa: E501


        :return: The s3_compatible of this SourceForListImportTasksOutput.  # noqa: E501
        :rtype: S3CompatibleForListImportTasksOutput
        """
        return self._s3_compatible

    @s3_compatible.setter
    def s3_compatible(self, s3_compatible):
        """Sets the s3_compatible of this SourceForListImportTasksOutput.


        :param s3_compatible: The s3_compatible of this SourceForListImportTasksOutput.  # noqa: E501
        :type: S3CompatibleForListImportTasksOutput
        """

        self._s3_compatible = s3_compatible

    @property
    def target_table_infos(self):
        """Gets the target_table_infos of this SourceForListImportTasksOutput.  # noqa: E501


        :return: The target_table_infos of this SourceForListImportTasksOutput.  # noqa: E501
        :rtype: list[TargetTableInfoForListImportTasksOutput]
        """
        return self._target_table_infos

    @target_table_infos.setter
    def target_table_infos(self, target_table_infos):
        """Sets the target_table_infos of this SourceForListImportTasksOutput.


        :param target_table_infos: The target_table_infos of this SourceForListImportTasksOutput.  # noqa: E501
        :type: list[TargetTableInfoForListImportTasksOutput]
        """

        self._target_table_infos = target_table_infos

    @property
    def tos(self):
        """Gets the tos of this SourceForListImportTasksOutput.  # noqa: E501


        :return: The tos of this SourceForListImportTasksOutput.  # noqa: E501
        :rtype: TosForListImportTasksOutput
        """
        return self._tos

    @tos.setter
    def tos(self, tos):
        """Sets the tos of this SourceForListImportTasksOutput.


        :param tos: The tos of this SourceForListImportTasksOutput.  # noqa: E501
        :type: TosForListImportTasksOutput
        """

        self._tos = tos

    @property
    def type(self):
        """Gets the type of this SourceForListImportTasksOutput.  # noqa: E501


        :return: The type of this SourceForListImportTasksOutput.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this SourceForListImportTasksOutput.


        :param type: The type of this SourceForListImportTasksOutput.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SourceForListImportTasksOutput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SourceForListImportTasksOutput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SourceForListImportTasksOutput):
            return True

        return self.to_dict() != other.to_dict()
