# coding: utf-8

"""
    seccenter20240508

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class ConditionsForDownloadAIVulnListInput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cve_id': 'str',
        'is_real_risk_vul': 'bool',
        'level': 'list[str]',
        'tag': 'list[str]',
        'vuln_name': 'str'
    }

    attribute_map = {
        'cve_id': 'CveID',
        'is_real_risk_vul': 'IsRealRiskVul',
        'level': 'Level',
        'tag': 'Tag',
        'vuln_name': 'VulnName'
    }

    def __init__(self, cve_id=None, is_real_risk_vul=None, level=None, tag=None, vuln_name=None, _configuration=None):  # noqa: E501
        """ConditionsForDownloadAIVulnListInput - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._cve_id = None
        self._is_real_risk_vul = None
        self._level = None
        self._tag = None
        self._vuln_name = None
        self.discriminator = None

        if cve_id is not None:
            self.cve_id = cve_id
        if is_real_risk_vul is not None:
            self.is_real_risk_vul = is_real_risk_vul
        if level is not None:
            self.level = level
        if tag is not None:
            self.tag = tag
        if vuln_name is not None:
            self.vuln_name = vuln_name

    @property
    def cve_id(self):
        """Gets the cve_id of this ConditionsForDownloadAIVulnListInput.  # noqa: E501


        :return: The cve_id of this ConditionsForDownloadAIVulnListInput.  # noqa: E501
        :rtype: str
        """
        return self._cve_id

    @cve_id.setter
    def cve_id(self, cve_id):
        """Sets the cve_id of this ConditionsForDownloadAIVulnListInput.


        :param cve_id: The cve_id of this ConditionsForDownloadAIVulnListInput.  # noqa: E501
        :type: str
        """

        self._cve_id = cve_id

    @property
    def is_real_risk_vul(self):
        """Gets the is_real_risk_vul of this ConditionsForDownloadAIVulnListInput.  # noqa: E501


        :return: The is_real_risk_vul of this ConditionsForDownloadAIVulnListInput.  # noqa: E501
        :rtype: bool
        """
        return self._is_real_risk_vul

    @is_real_risk_vul.setter
    def is_real_risk_vul(self, is_real_risk_vul):
        """Sets the is_real_risk_vul of this ConditionsForDownloadAIVulnListInput.


        :param is_real_risk_vul: The is_real_risk_vul of this ConditionsForDownloadAIVulnListInput.  # noqa: E501
        :type: bool
        """

        self._is_real_risk_vul = is_real_risk_vul

    @property
    def level(self):
        """Gets the level of this ConditionsForDownloadAIVulnListInput.  # noqa: E501


        :return: The level of this ConditionsForDownloadAIVulnListInput.  # noqa: E501
        :rtype: list[str]
        """
        return self._level

    @level.setter
    def level(self, level):
        """Sets the level of this ConditionsForDownloadAIVulnListInput.


        :param level: The level of this ConditionsForDownloadAIVulnListInput.  # noqa: E501
        :type: list[str]
        """

        self._level = level

    @property
    def tag(self):
        """Gets the tag of this ConditionsForDownloadAIVulnListInput.  # noqa: E501


        :return: The tag of this ConditionsForDownloadAIVulnListInput.  # noqa: E501
        :rtype: list[str]
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this ConditionsForDownloadAIVulnListInput.


        :param tag: The tag of this ConditionsForDownloadAIVulnListInput.  # noqa: E501
        :type: list[str]
        """

        self._tag = tag

    @property
    def vuln_name(self):
        """Gets the vuln_name of this ConditionsForDownloadAIVulnListInput.  # noqa: E501


        :return: The vuln_name of this ConditionsForDownloadAIVulnListInput.  # noqa: E501
        :rtype: str
        """
        return self._vuln_name

    @vuln_name.setter
    def vuln_name(self, vuln_name):
        """Sets the vuln_name of this ConditionsForDownloadAIVulnListInput.


        :param vuln_name: The vuln_name of this ConditionsForDownloadAIVulnListInput.  # noqa: E501
        :type: str
        """

        self._vuln_name = vuln_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConditionsForDownloadAIVulnListInput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConditionsForDownloadAIVulnListInput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ConditionsForDownloadAIVulnListInput):
            return True

        return self.to_dict() != other.to_dict()
