# coding: utf-8

"""
    seccenter20240508

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class DataForListVulDetailOutput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'account_id': 'str',
        'agent_id': 'str',
        'cluster_name': 'str',
        'container_name': 'str',
        'control_time': 'str',
        'create_time': 'str',
        'cves': 'list[str]',
        'cwpp_id': 'str',
        'eip_address': 'str',
        'fix_command_list': 'list[str]',
        'hostname': 'str',
        'image_name': 'str',
        'level': 'str',
        'operate_reason': 'str',
        'pod_id': 'str',
        'pod_name': 'str',
        'primary_ip_address': 'str',
        'refer_url': 'str',
        'software_list': 'list[SoftwareListForListVulDetailOutput]',
        'solution_cn': 'str',
        'status': 'str',
        'tag': 'list[str]',
        'tags': 'list[str]',
        'update_time': 'str',
        'vul_ident_id': 'str',
        'vuln_name': 'str',
        'vuln_name_en': 'str',
        'workload_name': 'str'
    }

    attribute_map = {
        'account_id': 'AccountID',
        'agent_id': 'AgentID',
        'cluster_name': 'ClusterName',
        'container_name': 'ContainerName',
        'control_time': 'ControlTime',
        'create_time': 'CreateTime',
        'cves': 'Cves',
        'cwpp_id': 'CwppID',
        'eip_address': 'EipAddress',
        'fix_command_list': 'FixCommandList',
        'hostname': 'Hostname',
        'image_name': 'ImageName',
        'level': 'Level',
        'operate_reason': 'OperateReason',
        'pod_id': 'PodID',
        'pod_name': 'PodName',
        'primary_ip_address': 'PrimaryIpAddress',
        'refer_url': 'ReferUrl',
        'software_list': 'SoftwareList',
        'solution_cn': 'SolutionCn',
        'status': 'Status',
        'tag': 'Tag',
        'tags': 'Tags',
        'update_time': 'UpdateTime',
        'vul_ident_id': 'VulIdentID',
        'vuln_name': 'VulnName',
        'vuln_name_en': 'VulnNameEn',
        'workload_name': 'WorkloadName'
    }

    def __init__(self, account_id=None, agent_id=None, cluster_name=None, container_name=None, control_time=None, create_time=None, cves=None, cwpp_id=None, eip_address=None, fix_command_list=None, hostname=None, image_name=None, level=None, operate_reason=None, pod_id=None, pod_name=None, primary_ip_address=None, refer_url=None, software_list=None, solution_cn=None, status=None, tag=None, tags=None, update_time=None, vul_ident_id=None, vuln_name=None, vuln_name_en=None, workload_name=None, _configuration=None):  # noqa: E501
        """DataForListVulDetailOutput - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._account_id = None
        self._agent_id = None
        self._cluster_name = None
        self._container_name = None
        self._control_time = None
        self._create_time = None
        self._cves = None
        self._cwpp_id = None
        self._eip_address = None
        self._fix_command_list = None
        self._hostname = None
        self._image_name = None
        self._level = None
        self._operate_reason = None
        self._pod_id = None
        self._pod_name = None
        self._primary_ip_address = None
        self._refer_url = None
        self._software_list = None
        self._solution_cn = None
        self._status = None
        self._tag = None
        self._tags = None
        self._update_time = None
        self._vul_ident_id = None
        self._vuln_name = None
        self._vuln_name_en = None
        self._workload_name = None
        self.discriminator = None

        if account_id is not None:
            self.account_id = account_id
        if agent_id is not None:
            self.agent_id = agent_id
        if cluster_name is not None:
            self.cluster_name = cluster_name
        if container_name is not None:
            self.container_name = container_name
        if control_time is not None:
            self.control_time = control_time
        if create_time is not None:
            self.create_time = create_time
        if cves is not None:
            self.cves = cves
        if cwpp_id is not None:
            self.cwpp_id = cwpp_id
        if eip_address is not None:
            self.eip_address = eip_address
        if fix_command_list is not None:
            self.fix_command_list = fix_command_list
        if hostname is not None:
            self.hostname = hostname
        if image_name is not None:
            self.image_name = image_name
        if level is not None:
            self.level = level
        if operate_reason is not None:
            self.operate_reason = operate_reason
        if pod_id is not None:
            self.pod_id = pod_id
        if pod_name is not None:
            self.pod_name = pod_name
        if primary_ip_address is not None:
            self.primary_ip_address = primary_ip_address
        if refer_url is not None:
            self.refer_url = refer_url
        if software_list is not None:
            self.software_list = software_list
        if solution_cn is not None:
            self.solution_cn = solution_cn
        if status is not None:
            self.status = status
        if tag is not None:
            self.tag = tag
        if tags is not None:
            self.tags = tags
        if update_time is not None:
            self.update_time = update_time
        if vul_ident_id is not None:
            self.vul_ident_id = vul_ident_id
        if vuln_name is not None:
            self.vuln_name = vuln_name
        if vuln_name_en is not None:
            self.vuln_name_en = vuln_name_en
        if workload_name is not None:
            self.workload_name = workload_name

    @property
    def account_id(self):
        """Gets the account_id of this DataForListVulDetailOutput.  # noqa: E501


        :return: The account_id of this DataForListVulDetailOutput.  # noqa: E501
        :rtype: str
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """Sets the account_id of this DataForListVulDetailOutput.


        :param account_id: The account_id of this DataForListVulDetailOutput.  # noqa: E501
        :type: str
        """

        self._account_id = account_id

    @property
    def agent_id(self):
        """Gets the agent_id of this DataForListVulDetailOutput.  # noqa: E501


        :return: The agent_id of this DataForListVulDetailOutput.  # noqa: E501
        :rtype: str
        """
        return self._agent_id

    @agent_id.setter
    def agent_id(self, agent_id):
        """Sets the agent_id of this DataForListVulDetailOutput.


        :param agent_id: The agent_id of this DataForListVulDetailOutput.  # noqa: E501
        :type: str
        """

        self._agent_id = agent_id

    @property
    def cluster_name(self):
        """Gets the cluster_name of this DataForListVulDetailOutput.  # noqa: E501


        :return: The cluster_name of this DataForListVulDetailOutput.  # noqa: E501
        :rtype: str
        """
        return self._cluster_name

    @cluster_name.setter
    def cluster_name(self, cluster_name):
        """Sets the cluster_name of this DataForListVulDetailOutput.


        :param cluster_name: The cluster_name of this DataForListVulDetailOutput.  # noqa: E501
        :type: str
        """

        self._cluster_name = cluster_name

    @property
    def container_name(self):
        """Gets the container_name of this DataForListVulDetailOutput.  # noqa: E501


        :return: The container_name of this DataForListVulDetailOutput.  # noqa: E501
        :rtype: str
        """
        return self._container_name

    @container_name.setter
    def container_name(self, container_name):
        """Sets the container_name of this DataForListVulDetailOutput.


        :param container_name: The container_name of this DataForListVulDetailOutput.  # noqa: E501
        :type: str
        """

        self._container_name = container_name

    @property
    def control_time(self):
        """Gets the control_time of this DataForListVulDetailOutput.  # noqa: E501


        :return: The control_time of this DataForListVulDetailOutput.  # noqa: E501
        :rtype: str
        """
        return self._control_time

    @control_time.setter
    def control_time(self, control_time):
        """Sets the control_time of this DataForListVulDetailOutput.


        :param control_time: The control_time of this DataForListVulDetailOutput.  # noqa: E501
        :type: str
        """

        self._control_time = control_time

    @property
    def create_time(self):
        """Gets the create_time of this DataForListVulDetailOutput.  # noqa: E501


        :return: The create_time of this DataForListVulDetailOutput.  # noqa: E501
        :rtype: str
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this DataForListVulDetailOutput.


        :param create_time: The create_time of this DataForListVulDetailOutput.  # noqa: E501
        :type: str
        """

        self._create_time = create_time

    @property
    def cves(self):
        """Gets the cves of this DataForListVulDetailOutput.  # noqa: E501


        :return: The cves of this DataForListVulDetailOutput.  # noqa: E501
        :rtype: list[str]
        """
        return self._cves

    @cves.setter
    def cves(self, cves):
        """Sets the cves of this DataForListVulDetailOutput.


        :param cves: The cves of this DataForListVulDetailOutput.  # noqa: E501
        :type: list[str]
        """

        self._cves = cves

    @property
    def cwpp_id(self):
        """Gets the cwpp_id of this DataForListVulDetailOutput.  # noqa: E501


        :return: The cwpp_id of this DataForListVulDetailOutput.  # noqa: E501
        :rtype: str
        """
        return self._cwpp_id

    @cwpp_id.setter
    def cwpp_id(self, cwpp_id):
        """Sets the cwpp_id of this DataForListVulDetailOutput.


        :param cwpp_id: The cwpp_id of this DataForListVulDetailOutput.  # noqa: E501
        :type: str
        """

        self._cwpp_id = cwpp_id

    @property
    def eip_address(self):
        """Gets the eip_address of this DataForListVulDetailOutput.  # noqa: E501


        :return: The eip_address of this DataForListVulDetailOutput.  # noqa: E501
        :rtype: str
        """
        return self._eip_address

    @eip_address.setter
    def eip_address(self, eip_address):
        """Sets the eip_address of this DataForListVulDetailOutput.


        :param eip_address: The eip_address of this DataForListVulDetailOutput.  # noqa: E501
        :type: str
        """

        self._eip_address = eip_address

    @property
    def fix_command_list(self):
        """Gets the fix_command_list of this DataForListVulDetailOutput.  # noqa: E501


        :return: The fix_command_list of this DataForListVulDetailOutput.  # noqa: E501
        :rtype: list[str]
        """
        return self._fix_command_list

    @fix_command_list.setter
    def fix_command_list(self, fix_command_list):
        """Sets the fix_command_list of this DataForListVulDetailOutput.


        :param fix_command_list: The fix_command_list of this DataForListVulDetailOutput.  # noqa: E501
        :type: list[str]
        """

        self._fix_command_list = fix_command_list

    @property
    def hostname(self):
        """Gets the hostname of this DataForListVulDetailOutput.  # noqa: E501


        :return: The hostname of this DataForListVulDetailOutput.  # noqa: E501
        :rtype: str
        """
        return self._hostname

    @hostname.setter
    def hostname(self, hostname):
        """Sets the hostname of this DataForListVulDetailOutput.


        :param hostname: The hostname of this DataForListVulDetailOutput.  # noqa: E501
        :type: str
        """

        self._hostname = hostname

    @property
    def image_name(self):
        """Gets the image_name of this DataForListVulDetailOutput.  # noqa: E501


        :return: The image_name of this DataForListVulDetailOutput.  # noqa: E501
        :rtype: str
        """
        return self._image_name

    @image_name.setter
    def image_name(self, image_name):
        """Sets the image_name of this DataForListVulDetailOutput.


        :param image_name: The image_name of this DataForListVulDetailOutput.  # noqa: E501
        :type: str
        """

        self._image_name = image_name

    @property
    def level(self):
        """Gets the level of this DataForListVulDetailOutput.  # noqa: E501


        :return: The level of this DataForListVulDetailOutput.  # noqa: E501
        :rtype: str
        """
        return self._level

    @level.setter
    def level(self, level):
        """Sets the level of this DataForListVulDetailOutput.


        :param level: The level of this DataForListVulDetailOutput.  # noqa: E501
        :type: str
        """

        self._level = level

    @property
    def operate_reason(self):
        """Gets the operate_reason of this DataForListVulDetailOutput.  # noqa: E501


        :return: The operate_reason of this DataForListVulDetailOutput.  # noqa: E501
        :rtype: str
        """
        return self._operate_reason

    @operate_reason.setter
    def operate_reason(self, operate_reason):
        """Sets the operate_reason of this DataForListVulDetailOutput.


        :param operate_reason: The operate_reason of this DataForListVulDetailOutput.  # noqa: E501
        :type: str
        """

        self._operate_reason = operate_reason

    @property
    def pod_id(self):
        """Gets the pod_id of this DataForListVulDetailOutput.  # noqa: E501


        :return: The pod_id of this DataForListVulDetailOutput.  # noqa: E501
        :rtype: str
        """
        return self._pod_id

    @pod_id.setter
    def pod_id(self, pod_id):
        """Sets the pod_id of this DataForListVulDetailOutput.


        :param pod_id: The pod_id of this DataForListVulDetailOutput.  # noqa: E501
        :type: str
        """

        self._pod_id = pod_id

    @property
    def pod_name(self):
        """Gets the pod_name of this DataForListVulDetailOutput.  # noqa: E501


        :return: The pod_name of this DataForListVulDetailOutput.  # noqa: E501
        :rtype: str
        """
        return self._pod_name

    @pod_name.setter
    def pod_name(self, pod_name):
        """Sets the pod_name of this DataForListVulDetailOutput.


        :param pod_name: The pod_name of this DataForListVulDetailOutput.  # noqa: E501
        :type: str
        """

        self._pod_name = pod_name

    @property
    def primary_ip_address(self):
        """Gets the primary_ip_address of this DataForListVulDetailOutput.  # noqa: E501


        :return: The primary_ip_address of this DataForListVulDetailOutput.  # noqa: E501
        :rtype: str
        """
        return self._primary_ip_address

    @primary_ip_address.setter
    def primary_ip_address(self, primary_ip_address):
        """Sets the primary_ip_address of this DataForListVulDetailOutput.


        :param primary_ip_address: The primary_ip_address of this DataForListVulDetailOutput.  # noqa: E501
        :type: str
        """

        self._primary_ip_address = primary_ip_address

    @property
    def refer_url(self):
        """Gets the refer_url of this DataForListVulDetailOutput.  # noqa: E501


        :return: The refer_url of this DataForListVulDetailOutput.  # noqa: E501
        :rtype: str
        """
        return self._refer_url

    @refer_url.setter
    def refer_url(self, refer_url):
        """Sets the refer_url of this DataForListVulDetailOutput.


        :param refer_url: The refer_url of this DataForListVulDetailOutput.  # noqa: E501
        :type: str
        """

        self._refer_url = refer_url

    @property
    def software_list(self):
        """Gets the software_list of this DataForListVulDetailOutput.  # noqa: E501


        :return: The software_list of this DataForListVulDetailOutput.  # noqa: E501
        :rtype: list[SoftwareListForListVulDetailOutput]
        """
        return self._software_list

    @software_list.setter
    def software_list(self, software_list):
        """Sets the software_list of this DataForListVulDetailOutput.


        :param software_list: The software_list of this DataForListVulDetailOutput.  # noqa: E501
        :type: list[SoftwareListForListVulDetailOutput]
        """

        self._software_list = software_list

    @property
    def solution_cn(self):
        """Gets the solution_cn of this DataForListVulDetailOutput.  # noqa: E501


        :return: The solution_cn of this DataForListVulDetailOutput.  # noqa: E501
        :rtype: str
        """
        return self._solution_cn

    @solution_cn.setter
    def solution_cn(self, solution_cn):
        """Sets the solution_cn of this DataForListVulDetailOutput.


        :param solution_cn: The solution_cn of this DataForListVulDetailOutput.  # noqa: E501
        :type: str
        """

        self._solution_cn = solution_cn

    @property
    def status(self):
        """Gets the status of this DataForListVulDetailOutput.  # noqa: E501


        :return: The status of this DataForListVulDetailOutput.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this DataForListVulDetailOutput.


        :param status: The status of this DataForListVulDetailOutput.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def tag(self):
        """Gets the tag of this DataForListVulDetailOutput.  # noqa: E501


        :return: The tag of this DataForListVulDetailOutput.  # noqa: E501
        :rtype: list[str]
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this DataForListVulDetailOutput.


        :param tag: The tag of this DataForListVulDetailOutput.  # noqa: E501
        :type: list[str]
        """

        self._tag = tag

    @property
    def tags(self):
        """Gets the tags of this DataForListVulDetailOutput.  # noqa: E501


        :return: The tags of this DataForListVulDetailOutput.  # noqa: E501
        :rtype: list[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this DataForListVulDetailOutput.


        :param tags: The tags of this DataForListVulDetailOutput.  # noqa: E501
        :type: list[str]
        """

        self._tags = tags

    @property
    def update_time(self):
        """Gets the update_time of this DataForListVulDetailOutput.  # noqa: E501


        :return: The update_time of this DataForListVulDetailOutput.  # noqa: E501
        :rtype: str
        """
        return self._update_time

    @update_time.setter
    def update_time(self, update_time):
        """Sets the update_time of this DataForListVulDetailOutput.


        :param update_time: The update_time of this DataForListVulDetailOutput.  # noqa: E501
        :type: str
        """

        self._update_time = update_time

    @property
    def vul_ident_id(self):
        """Gets the vul_ident_id of this DataForListVulDetailOutput.  # noqa: E501


        :return: The vul_ident_id of this DataForListVulDetailOutput.  # noqa: E501
        :rtype: str
        """
        return self._vul_ident_id

    @vul_ident_id.setter
    def vul_ident_id(self, vul_ident_id):
        """Sets the vul_ident_id of this DataForListVulDetailOutput.


        :param vul_ident_id: The vul_ident_id of this DataForListVulDetailOutput.  # noqa: E501
        :type: str
        """

        self._vul_ident_id = vul_ident_id

    @property
    def vuln_name(self):
        """Gets the vuln_name of this DataForListVulDetailOutput.  # noqa: E501


        :return: The vuln_name of this DataForListVulDetailOutput.  # noqa: E501
        :rtype: str
        """
        return self._vuln_name

    @vuln_name.setter
    def vuln_name(self, vuln_name):
        """Sets the vuln_name of this DataForListVulDetailOutput.


        :param vuln_name: The vuln_name of this DataForListVulDetailOutput.  # noqa: E501
        :type: str
        """

        self._vuln_name = vuln_name

    @property
    def vuln_name_en(self):
        """Gets the vuln_name_en of this DataForListVulDetailOutput.  # noqa: E501


        :return: The vuln_name_en of this DataForListVulDetailOutput.  # noqa: E501
        :rtype: str
        """
        return self._vuln_name_en

    @vuln_name_en.setter
    def vuln_name_en(self, vuln_name_en):
        """Sets the vuln_name_en of this DataForListVulDetailOutput.


        :param vuln_name_en: The vuln_name_en of this DataForListVulDetailOutput.  # noqa: E501
        :type: str
        """

        self._vuln_name_en = vuln_name_en

    @property
    def workload_name(self):
        """Gets the workload_name of this DataForListVulDetailOutput.  # noqa: E501


        :return: The workload_name of this DataForListVulDetailOutput.  # noqa: E501
        :rtype: str
        """
        return self._workload_name

    @workload_name.setter
    def workload_name(self, workload_name):
        """Sets the workload_name of this DataForListVulDetailOutput.


        :param workload_name: The workload_name of this DataForListVulDetailOutput.  # noqa: E501
        :type: str
        """

        self._workload_name = workload_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DataForListVulDetailOutput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataForListVulDetailOutput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DataForListVulDetailOutput):
            return True

        return self.to_dict() != other.to_dict()
