# coding: utf-8

"""
    seccenter20240508

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class ListBatchEndpointHandleMethodsResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'operation_list': 'list[OperationListForListBatchEndpointHandleMethodsOutput]',
        'support': 'bool'
    }

    attribute_map = {
        'operation_list': 'OperationList',
        'support': 'Support'
    }

    def __init__(self, operation_list=None, support=None, _configuration=None):  # noqa: E501
        """ListBatchEndpointHandleMethodsResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._operation_list = None
        self._support = None
        self.discriminator = None

        if operation_list is not None:
            self.operation_list = operation_list
        if support is not None:
            self.support = support

    @property
    def operation_list(self):
        """Gets the operation_list of this ListBatchEndpointHandleMethodsResponse.  # noqa: E501


        :return: The operation_list of this ListBatchEndpointHandleMethodsResponse.  # noqa: E501
        :rtype: list[OperationListForListBatchEndpointHandleMethodsOutput]
        """
        return self._operation_list

    @operation_list.setter
    def operation_list(self, operation_list):
        """Sets the operation_list of this ListBatchEndpointHandleMethodsResponse.


        :param operation_list: The operation_list of this ListBatchEndpointHandleMethodsResponse.  # noqa: E501
        :type: list[OperationListForListBatchEndpointHandleMethodsOutput]
        """

        self._operation_list = operation_list

    @property
    def support(self):
        """Gets the support of this ListBatchEndpointHandleMethodsResponse.  # noqa: E501


        :return: The support of this ListBatchEndpointHandleMethodsResponse.  # noqa: E501
        :rtype: bool
        """
        return self._support

    @support.setter
    def support(self, support):
        """Sets the support of this ListBatchEndpointHandleMethodsResponse.


        :param support: The support of this ListBatchEndpointHandleMethodsResponse.  # noqa: E501
        :type: bool
        """

        self._support = support

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ListBatchEndpointHandleMethodsResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListBatchEndpointHandleMethodsResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ListBatchEndpointHandleMethodsResponse):
            return True

        return self.to_dict() != other.to_dict()
