# coding: utf-8

"""
    i18n_openapi

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class DocumentTaskCreateRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'comment': 'str',
        'deadline': 'str',
        'doc_url_list': 'list[DocUrlListForDocumentTaskCreateInput]',
        'procedures': 'int',
        'project_id': 'int',
        'proofread_type': 'int',
        'reference_doc_item': 'ReferenceDocItemForDocumentTaskCreateInput',
        'source_locale': 'str',
        'target_locale': 'list[str]',
        'task_name': 'str',
        'translator_type': 'int',
        'use_tm': 'bool'
    }

    attribute_map = {
        'comment': 'comment',
        'deadline': 'deadline',
        'doc_url_list': 'docUrlList',
        'procedures': 'procedures',
        'project_id': 'projectId',
        'proofread_type': 'proofreadType',
        'reference_doc_item': 'referenceDocItem',
        'source_locale': 'sourceLocale',
        'target_locale': 'targetLocale',
        'task_name': 'taskName',
        'translator_type': 'translatorType',
        'use_tm': 'useTM'
    }

    def __init__(self, comment=None, deadline=None, doc_url_list=None, procedures=None, project_id=None, proofread_type=None, reference_doc_item=None, source_locale=None, target_locale=None, task_name=None, translator_type=None, use_tm=None, _configuration=None):  # noqa: E501
        """DocumentTaskCreateRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._comment = None
        self._deadline = None
        self._doc_url_list = None
        self._procedures = None
        self._project_id = None
        self._proofread_type = None
        self._reference_doc_item = None
        self._source_locale = None
        self._target_locale = None
        self._task_name = None
        self._translator_type = None
        self._use_tm = None
        self.discriminator = None

        if comment is not None:
            self.comment = comment
        self.deadline = deadline
        if doc_url_list is not None:
            self.doc_url_list = doc_url_list
        if procedures is not None:
            self.procedures = procedures
        self.project_id = project_id
        if proofread_type is not None:
            self.proofread_type = proofread_type
        if reference_doc_item is not None:
            self.reference_doc_item = reference_doc_item
        if source_locale is not None:
            self.source_locale = source_locale
        if target_locale is not None:
            self.target_locale = target_locale
        self.task_name = task_name
        if translator_type is not None:
            self.translator_type = translator_type
        if use_tm is not None:
            self.use_tm = use_tm

    @property
    def comment(self):
        """Gets the comment of this DocumentTaskCreateRequest.  # noqa: E501


        :return: The comment of this DocumentTaskCreateRequest.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this DocumentTaskCreateRequest.


        :param comment: The comment of this DocumentTaskCreateRequest.  # noqa: E501
        :type: str
        """

        self._comment = comment

    @property
    def deadline(self):
        """Gets the deadline of this DocumentTaskCreateRequest.  # noqa: E501


        :return: The deadline of this DocumentTaskCreateRequest.  # noqa: E501
        :rtype: str
        """
        return self._deadline

    @deadline.setter
    def deadline(self, deadline):
        """Sets the deadline of this DocumentTaskCreateRequest.


        :param deadline: The deadline of this DocumentTaskCreateRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and deadline is None:
            raise ValueError("Invalid value for `deadline`, must not be `None`")  # noqa: E501

        self._deadline = deadline

    @property
    def doc_url_list(self):
        """Gets the doc_url_list of this DocumentTaskCreateRequest.  # noqa: E501


        :return: The doc_url_list of this DocumentTaskCreateRequest.  # noqa: E501
        :rtype: list[DocUrlListForDocumentTaskCreateInput]
        """
        return self._doc_url_list

    @doc_url_list.setter
    def doc_url_list(self, doc_url_list):
        """Sets the doc_url_list of this DocumentTaskCreateRequest.


        :param doc_url_list: The doc_url_list of this DocumentTaskCreateRequest.  # noqa: E501
        :type: list[DocUrlListForDocumentTaskCreateInput]
        """

        self._doc_url_list = doc_url_list

    @property
    def procedures(self):
        """Gets the procedures of this DocumentTaskCreateRequest.  # noqa: E501


        :return: The procedures of this DocumentTaskCreateRequest.  # noqa: E501
        :rtype: int
        """
        return self._procedures

    @procedures.setter
    def procedures(self, procedures):
        """Sets the procedures of this DocumentTaskCreateRequest.


        :param procedures: The procedures of this DocumentTaskCreateRequest.  # noqa: E501
        :type: int
        """
        if (self._configuration.client_side_validation and
                procedures is not None and procedures > 3):  # noqa: E501
            raise ValueError("Invalid value for `procedures`, must be a value less than or equal to `3`")  # noqa: E501
        if (self._configuration.client_side_validation and
                procedures is not None and procedures < 1):  # noqa: E501
            raise ValueError("Invalid value for `procedures`, must be a value greater than or equal to `1`")  # noqa: E501

        self._procedures = procedures

    @property
    def project_id(self):
        """Gets the project_id of this DocumentTaskCreateRequest.  # noqa: E501


        :return: The project_id of this DocumentTaskCreateRequest.  # noqa: E501
        :rtype: int
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this DocumentTaskCreateRequest.


        :param project_id: The project_id of this DocumentTaskCreateRequest.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and project_id is None:
            raise ValueError("Invalid value for `project_id`, must not be `None`")  # noqa: E501

        self._project_id = project_id

    @property
    def proofread_type(self):
        """Gets the proofread_type of this DocumentTaskCreateRequest.  # noqa: E501


        :return: The proofread_type of this DocumentTaskCreateRequest.  # noqa: E501
        :rtype: int
        """
        return self._proofread_type

    @proofread_type.setter
    def proofread_type(self, proofread_type):
        """Sets the proofread_type of this DocumentTaskCreateRequest.


        :param proofread_type: The proofread_type of this DocumentTaskCreateRequest.  # noqa: E501
        :type: int
        """
        if (self._configuration.client_side_validation and
                proofread_type is not None and proofread_type > 1):  # noqa: E501
            raise ValueError("Invalid value for `proofread_type`, must be a value less than or equal to `1`")  # noqa: E501
        if (self._configuration.client_side_validation and
                proofread_type is not None and proofread_type < 0):  # noqa: E501
            raise ValueError("Invalid value for `proofread_type`, must be a value greater than or equal to `0`")  # noqa: E501

        self._proofread_type = proofread_type

    @property
    def reference_doc_item(self):
        """Gets the reference_doc_item of this DocumentTaskCreateRequest.  # noqa: E501


        :return: The reference_doc_item of this DocumentTaskCreateRequest.  # noqa: E501
        :rtype: ReferenceDocItemForDocumentTaskCreateInput
        """
        return self._reference_doc_item

    @reference_doc_item.setter
    def reference_doc_item(self, reference_doc_item):
        """Sets the reference_doc_item of this DocumentTaskCreateRequest.


        :param reference_doc_item: The reference_doc_item of this DocumentTaskCreateRequest.  # noqa: E501
        :type: ReferenceDocItemForDocumentTaskCreateInput
        """

        self._reference_doc_item = reference_doc_item

    @property
    def source_locale(self):
        """Gets the source_locale of this DocumentTaskCreateRequest.  # noqa: E501


        :return: The source_locale of this DocumentTaskCreateRequest.  # noqa: E501
        :rtype: str
        """
        return self._source_locale

    @source_locale.setter
    def source_locale(self, source_locale):
        """Sets the source_locale of this DocumentTaskCreateRequest.


        :param source_locale: The source_locale of this DocumentTaskCreateRequest.  # noqa: E501
        :type: str
        """

        self._source_locale = source_locale

    @property
    def target_locale(self):
        """Gets the target_locale of this DocumentTaskCreateRequest.  # noqa: E501


        :return: The target_locale of this DocumentTaskCreateRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._target_locale

    @target_locale.setter
    def target_locale(self, target_locale):
        """Sets the target_locale of this DocumentTaskCreateRequest.


        :param target_locale: The target_locale of this DocumentTaskCreateRequest.  # noqa: E501
        :type: list[str]
        """

        self._target_locale = target_locale

    @property
    def task_name(self):
        """Gets the task_name of this DocumentTaskCreateRequest.  # noqa: E501


        :return: The task_name of this DocumentTaskCreateRequest.  # noqa: E501
        :rtype: str
        """
        return self._task_name

    @task_name.setter
    def task_name(self, task_name):
        """Sets the task_name of this DocumentTaskCreateRequest.


        :param task_name: The task_name of this DocumentTaskCreateRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and task_name is None:
            raise ValueError("Invalid value for `task_name`, must not be `None`")  # noqa: E501

        self._task_name = task_name

    @property
    def translator_type(self):
        """Gets the translator_type of this DocumentTaskCreateRequest.  # noqa: E501


        :return: The translator_type of this DocumentTaskCreateRequest.  # noqa: E501
        :rtype: int
        """
        return self._translator_type

    @translator_type.setter
    def translator_type(self, translator_type):
        """Sets the translator_type of this DocumentTaskCreateRequest.


        :param translator_type: The translator_type of this DocumentTaskCreateRequest.  # noqa: E501
        :type: int
        """
        if (self._configuration.client_side_validation and
                translator_type is not None and translator_type > 1):  # noqa: E501
            raise ValueError("Invalid value for `translator_type`, must be a value less than or equal to `1`")  # noqa: E501
        if (self._configuration.client_side_validation and
                translator_type is not None and translator_type < 0):  # noqa: E501
            raise ValueError("Invalid value for `translator_type`, must be a value greater than or equal to `0`")  # noqa: E501

        self._translator_type = translator_type

    @property
    def use_tm(self):
        """Gets the use_tm of this DocumentTaskCreateRequest.  # noqa: E501


        :return: The use_tm of this DocumentTaskCreateRequest.  # noqa: E501
        :rtype: bool
        """
        return self._use_tm

    @use_tm.setter
    def use_tm(self, use_tm):
        """Sets the use_tm of this DocumentTaskCreateRequest.


        :param use_tm: The use_tm of this DocumentTaskCreateRequest.  # noqa: E501
        :type: bool
        """

        self._use_tm = use_tm

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DocumentTaskCreateRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DocumentTaskCreateRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DocumentTaskCreateRequest):
            return True

        return self.to_dict() != other.to_dict()
