# coding: utf-8

"""
    i18n_openapi

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class VideoProjectAddTargetLangsToExistingDramaRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bgm_policy': 'int',
        'deadline': 'str',
        'drama_id': 'str',
        'dub_voice_mode': 'int',
        'from_task_type': 'int',
        'is_dub': 'bool',
        'project_id': 'str',
        'target_languages': 'list[str]',
        'target_style_map': 'TargetStyleMapForVideoProjectAddTargetLangsToExistingDramaInput',
        'video_identifiers': 'list[VideoIdentifierForVideoProjectAddTargetLangsToExistingDramaInput]',
        'video_speed_policy': 'int'
    }

    attribute_map = {
        'bgm_policy': 'bgmPolicy',
        'deadline': 'deadline',
        'drama_id': 'dramaId',
        'dub_voice_mode': 'dubVoiceMode',
        'from_task_type': 'fromTaskType',
        'is_dub': 'isDub',
        'project_id': 'projectId',
        'target_languages': 'targetLanguages',
        'target_style_map': 'targetStyleMap',
        'video_identifiers': 'videoIdentifiers',
        'video_speed_policy': 'videoSpeedPolicy'
    }

    def __init__(self, bgm_policy=None, deadline=None, drama_id=None, dub_voice_mode=None, from_task_type=None, is_dub=None, project_id=None, target_languages=None, target_style_map=None, video_identifiers=None, video_speed_policy=None, _configuration=None):  # noqa: E501
        """VideoProjectAddTargetLangsToExistingDramaRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._bgm_policy = None
        self._deadline = None
        self._drama_id = None
        self._dub_voice_mode = None
        self._from_task_type = None
        self._is_dub = None
        self._project_id = None
        self._target_languages = None
        self._target_style_map = None
        self._video_identifiers = None
        self._video_speed_policy = None
        self.discriminator = None

        if bgm_policy is not None:
            self.bgm_policy = bgm_policy
        if deadline is not None:
            self.deadline = deadline
        self.drama_id = drama_id
        if dub_voice_mode is not None:
            self.dub_voice_mode = dub_voice_mode
        self.from_task_type = from_task_type
        if is_dub is not None:
            self.is_dub = is_dub
        self.project_id = project_id
        if target_languages is not None:
            self.target_languages = target_languages
        if target_style_map is not None:
            self.target_style_map = target_style_map
        if video_identifiers is not None:
            self.video_identifiers = video_identifiers
        if video_speed_policy is not None:
            self.video_speed_policy = video_speed_policy

    @property
    def bgm_policy(self):
        """Gets the bgm_policy of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501


        :return: The bgm_policy of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501
        :rtype: int
        """
        return self._bgm_policy

    @bgm_policy.setter
    def bgm_policy(self, bgm_policy):
        """Sets the bgm_policy of this VideoProjectAddTargetLangsToExistingDramaRequest.


        :param bgm_policy: The bgm_policy of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501
        :type: int
        """

        self._bgm_policy = bgm_policy

    @property
    def deadline(self):
        """Gets the deadline of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501


        :return: The deadline of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501
        :rtype: str
        """
        return self._deadline

    @deadline.setter
    def deadline(self, deadline):
        """Sets the deadline of this VideoProjectAddTargetLangsToExistingDramaRequest.


        :param deadline: The deadline of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501
        :type: str
        """

        self._deadline = deadline

    @property
    def drama_id(self):
        """Gets the drama_id of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501


        :return: The drama_id of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501
        :rtype: str
        """
        return self._drama_id

    @drama_id.setter
    def drama_id(self, drama_id):
        """Sets the drama_id of this VideoProjectAddTargetLangsToExistingDramaRequest.


        :param drama_id: The drama_id of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and drama_id is None:
            raise ValueError("Invalid value for `drama_id`, must not be `None`")  # noqa: E501

        self._drama_id = drama_id

    @property
    def dub_voice_mode(self):
        """Gets the dub_voice_mode of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501


        :return: The dub_voice_mode of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501
        :rtype: int
        """
        return self._dub_voice_mode

    @dub_voice_mode.setter
    def dub_voice_mode(self, dub_voice_mode):
        """Sets the dub_voice_mode of this VideoProjectAddTargetLangsToExistingDramaRequest.


        :param dub_voice_mode: The dub_voice_mode of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501
        :type: int
        """

        self._dub_voice_mode = dub_voice_mode

    @property
    def from_task_type(self):
        """Gets the from_task_type of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501


        :return: The from_task_type of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501
        :rtype: int
        """
        return self._from_task_type

    @from_task_type.setter
    def from_task_type(self, from_task_type):
        """Sets the from_task_type of this VideoProjectAddTargetLangsToExistingDramaRequest.


        :param from_task_type: The from_task_type of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and from_task_type is None:
            raise ValueError("Invalid value for `from_task_type`, must not be `None`")  # noqa: E501

        self._from_task_type = from_task_type

    @property
    def is_dub(self):
        """Gets the is_dub of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501


        :return: The is_dub of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501
        :rtype: bool
        """
        return self._is_dub

    @is_dub.setter
    def is_dub(self, is_dub):
        """Sets the is_dub of this VideoProjectAddTargetLangsToExistingDramaRequest.


        :param is_dub: The is_dub of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501
        :type: bool
        """

        self._is_dub = is_dub

    @property
    def project_id(self):
        """Gets the project_id of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501


        :return: The project_id of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this VideoProjectAddTargetLangsToExistingDramaRequest.


        :param project_id: The project_id of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and project_id is None:
            raise ValueError("Invalid value for `project_id`, must not be `None`")  # noqa: E501

        self._project_id = project_id

    @property
    def target_languages(self):
        """Gets the target_languages of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501


        :return: The target_languages of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._target_languages

    @target_languages.setter
    def target_languages(self, target_languages):
        """Sets the target_languages of this VideoProjectAddTargetLangsToExistingDramaRequest.


        :param target_languages: The target_languages of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501
        :type: list[str]
        """

        self._target_languages = target_languages

    @property
    def target_style_map(self):
        """Gets the target_style_map of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501


        :return: The target_style_map of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501
        :rtype: TargetStyleMapForVideoProjectAddTargetLangsToExistingDramaInput
        """
        return self._target_style_map

    @target_style_map.setter
    def target_style_map(self, target_style_map):
        """Sets the target_style_map of this VideoProjectAddTargetLangsToExistingDramaRequest.


        :param target_style_map: The target_style_map of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501
        :type: TargetStyleMapForVideoProjectAddTargetLangsToExistingDramaInput
        """

        self._target_style_map = target_style_map

    @property
    def video_identifiers(self):
        """Gets the video_identifiers of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501


        :return: The video_identifiers of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501
        :rtype: list[VideoIdentifierForVideoProjectAddTargetLangsToExistingDramaInput]
        """
        return self._video_identifiers

    @video_identifiers.setter
    def video_identifiers(self, video_identifiers):
        """Sets the video_identifiers of this VideoProjectAddTargetLangsToExistingDramaRequest.


        :param video_identifiers: The video_identifiers of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501
        :type: list[VideoIdentifierForVideoProjectAddTargetLangsToExistingDramaInput]
        """

        self._video_identifiers = video_identifiers

    @property
    def video_speed_policy(self):
        """Gets the video_speed_policy of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501


        :return: The video_speed_policy of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501
        :rtype: int
        """
        return self._video_speed_policy

    @video_speed_policy.setter
    def video_speed_policy(self, video_speed_policy):
        """Sets the video_speed_policy of this VideoProjectAddTargetLangsToExistingDramaRequest.


        :param video_speed_policy: The video_speed_policy of this VideoProjectAddTargetLangsToExistingDramaRequest.  # noqa: E501
        :type: int
        """

        self._video_speed_policy = video_speed_policy

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VideoProjectAddTargetLangsToExistingDramaRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VideoProjectAddTargetLangsToExistingDramaRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VideoProjectAddTargetLangsToExistingDramaRequest):
            return True

        return self.to_dict() != other.to_dict()
