# coding: utf-8

"""
    vod20260101

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class UpdateVodDomainConfigRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'domain_type': 'str',
        'preview_control': 'PreviewControlForUpdateVodDomainConfigInput',
        'real_time_process_switch': 'str',
        'rewrite_m3_u8_tag_control': 'RewriteM3U8TagControlForUpdateVodDomainConfigInput',
        'space_name': 'str',
        'update_cdn_config_param': 'UpdateCdnConfigParamForUpdateVodDomainConfigInput'
    }

    attribute_map = {
        'domain_type': 'DomainType',
        'preview_control': 'PreviewControl',
        'real_time_process_switch': 'RealTimeProcessSwitch',
        'rewrite_m3_u8_tag_control': 'RewriteM3U8TagControl',
        'space_name': 'SpaceName',
        'update_cdn_config_param': 'UpdateCdnConfigParam'
    }

    def __init__(self, domain_type=None, preview_control=None, real_time_process_switch=None, rewrite_m3_u8_tag_control=None, space_name=None, update_cdn_config_param=None, _configuration=None):  # noqa: E501
        """UpdateVodDomainConfigRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._domain_type = None
        self._preview_control = None
        self._real_time_process_switch = None
        self._rewrite_m3_u8_tag_control = None
        self._space_name = None
        self._update_cdn_config_param = None
        self.discriminator = None

        if domain_type is not None:
            self.domain_type = domain_type
        if preview_control is not None:
            self.preview_control = preview_control
        if real_time_process_switch is not None:
            self.real_time_process_switch = real_time_process_switch
        if rewrite_m3_u8_tag_control is not None:
            self.rewrite_m3_u8_tag_control = rewrite_m3_u8_tag_control
        self.space_name = space_name
        if update_cdn_config_param is not None:
            self.update_cdn_config_param = update_cdn_config_param

    @property
    def domain_type(self):
        """Gets the domain_type of this UpdateVodDomainConfigRequest.  # noqa: E501


        :return: The domain_type of this UpdateVodDomainConfigRequest.  # noqa: E501
        :rtype: str
        """
        return self._domain_type

    @domain_type.setter
    def domain_type(self, domain_type):
        """Sets the domain_type of this UpdateVodDomainConfigRequest.


        :param domain_type: The domain_type of this UpdateVodDomainConfigRequest.  # noqa: E501
        :type: str
        """

        self._domain_type = domain_type

    @property
    def preview_control(self):
        """Gets the preview_control of this UpdateVodDomainConfigRequest.  # noqa: E501


        :return: The preview_control of this UpdateVodDomainConfigRequest.  # noqa: E501
        :rtype: PreviewControlForUpdateVodDomainConfigInput
        """
        return self._preview_control

    @preview_control.setter
    def preview_control(self, preview_control):
        """Sets the preview_control of this UpdateVodDomainConfigRequest.


        :param preview_control: The preview_control of this UpdateVodDomainConfigRequest.  # noqa: E501
        :type: PreviewControlForUpdateVodDomainConfigInput
        """

        self._preview_control = preview_control

    @property
    def real_time_process_switch(self):
        """Gets the real_time_process_switch of this UpdateVodDomainConfigRequest.  # noqa: E501


        :return: The real_time_process_switch of this UpdateVodDomainConfigRequest.  # noqa: E501
        :rtype: str
        """
        return self._real_time_process_switch

    @real_time_process_switch.setter
    def real_time_process_switch(self, real_time_process_switch):
        """Sets the real_time_process_switch of this UpdateVodDomainConfigRequest.


        :param real_time_process_switch: The real_time_process_switch of this UpdateVodDomainConfigRequest.  # noqa: E501
        :type: str
        """

        self._real_time_process_switch = real_time_process_switch

    @property
    def rewrite_m3_u8_tag_control(self):
        """Gets the rewrite_m3_u8_tag_control of this UpdateVodDomainConfigRequest.  # noqa: E501


        :return: The rewrite_m3_u8_tag_control of this UpdateVodDomainConfigRequest.  # noqa: E501
        :rtype: RewriteM3U8TagControlForUpdateVodDomainConfigInput
        """
        return self._rewrite_m3_u8_tag_control

    @rewrite_m3_u8_tag_control.setter
    def rewrite_m3_u8_tag_control(self, rewrite_m3_u8_tag_control):
        """Sets the rewrite_m3_u8_tag_control of this UpdateVodDomainConfigRequest.


        :param rewrite_m3_u8_tag_control: The rewrite_m3_u8_tag_control of this UpdateVodDomainConfigRequest.  # noqa: E501
        :type: RewriteM3U8TagControlForUpdateVodDomainConfigInput
        """

        self._rewrite_m3_u8_tag_control = rewrite_m3_u8_tag_control

    @property
    def space_name(self):
        """Gets the space_name of this UpdateVodDomainConfigRequest.  # noqa: E501


        :return: The space_name of this UpdateVodDomainConfigRequest.  # noqa: E501
        :rtype: str
        """
        return self._space_name

    @space_name.setter
    def space_name(self, space_name):
        """Sets the space_name of this UpdateVodDomainConfigRequest.


        :param space_name: The space_name of this UpdateVodDomainConfigRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and space_name is None:
            raise ValueError("Invalid value for `space_name`, must not be `None`")  # noqa: E501

        self._space_name = space_name

    @property
    def update_cdn_config_param(self):
        """Gets the update_cdn_config_param of this UpdateVodDomainConfigRequest.  # noqa: E501


        :return: The update_cdn_config_param of this UpdateVodDomainConfigRequest.  # noqa: E501
        :rtype: UpdateCdnConfigParamForUpdateVodDomainConfigInput
        """
        return self._update_cdn_config_param

    @update_cdn_config_param.setter
    def update_cdn_config_param(self, update_cdn_config_param):
        """Sets the update_cdn_config_param of this UpdateVodDomainConfigRequest.


        :param update_cdn_config_param: The update_cdn_config_param of this UpdateVodDomainConfigRequest.  # noqa: E501
        :type: UpdateCdnConfigParamForUpdateVodDomainConfigInput
        """

        self._update_cdn_config_param = update_cdn_config_param

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateVodDomainConfigRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateVodDomainConfigRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UpdateVodDomainConfigRequest):
            return True

        return self.to_dict() != other.to_dict()
