# coding: utf-8

"""
    kafka

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class ItemForVerifyMigrateSubTasksInput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'config': 'str',
        'name': 'str',
        'type': 'str'
    }

    attribute_map = {
        'config': 'Config',
        'name': 'Name',
        'type': 'Type'
    }

    def __init__(self, config=None, name=None, type=None, _configuration=None):  # noqa: E501
        """ItemForVerifyMigrateSubTasksInput - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._config = None
        self._name = None
        self._type = None
        self.discriminator = None

        if config is not None:
            self.config = config
        if name is not None:
            self.name = name
        if type is not None:
            self.type = type

    @property
    def config(self):
        """Gets the config of this ItemForVerifyMigrateSubTasksInput.  # noqa: E501


        :return: The config of this ItemForVerifyMigrateSubTasksInput.  # noqa: E501
        :rtype: str
        """
        return self._config

    @config.setter
    def config(self, config):
        """Sets the config of this ItemForVerifyMigrateSubTasksInput.


        :param config: The config of this ItemForVerifyMigrateSubTasksInput.  # noqa: E501
        :type: str
        """

        self._config = config

    @property
    def name(self):
        """Gets the name of this ItemForVerifyMigrateSubTasksInput.  # noqa: E501


        :return: The name of this ItemForVerifyMigrateSubTasksInput.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ItemForVerifyMigrateSubTasksInput.


        :param name: The name of this ItemForVerifyMigrateSubTasksInput.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def type(self):
        """Gets the type of this ItemForVerifyMigrateSubTasksInput.  # noqa: E501


        :return: The type of this ItemForVerifyMigrateSubTasksInput.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ItemForVerifyMigrateSubTasksInput.


        :param type: The type of this ItemForVerifyMigrateSubTasksInput.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ItemForVerifyMigrateSubTasksInput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ItemForVerifyMigrateSubTasksInput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ItemForVerifyMigrateSubTasksInput):
            return True

        return self.to_dict() != other.to_dict()
