# coding: utf-8

"""
    cp

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class AdvancedConfigForTriggerManagedAppDeployInput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'app_monitoring_config': 'AppMonitoringConfigForTriggerManagedAppDeployInput',
        'app_storage_config_list': 'list[AppStorageConfigListForTriggerManagedAppDeployInput]',
        'custom_labels_and_annotations': 'CustomLabelsAndAnnotationsForTriggerManagedAppDeployInput',
        'env_variables': 'list[EnvVariableForTriggerManagedAppDeployInput]',
        'health_check': 'HealthCheckForTriggerManagedAppDeployInput',
        'service_access_config': 'ServiceAccessConfigForTriggerManagedAppDeployInput',
        'start_command': 'str',
        'start_config': 'StartConfigForTriggerManagedAppDeployInput',
        'start_parameter': 'str'
    }

    attribute_map = {
        'app_monitoring_config': 'AppMonitoringConfig',
        'app_storage_config_list': 'AppStorageConfigList',
        'custom_labels_and_annotations': 'CustomLabelsAndAnnotations',
        'env_variables': 'EnvVariables',
        'health_check': 'HealthCheck',
        'service_access_config': 'ServiceAccessConfig',
        'start_command': 'StartCommand',
        'start_config': 'StartConfig',
        'start_parameter': 'StartParameter'
    }

    def __init__(self, app_monitoring_config=None, app_storage_config_list=None, custom_labels_and_annotations=None, env_variables=None, health_check=None, service_access_config=None, start_command=None, start_config=None, start_parameter=None, _configuration=None):  # noqa: E501
        """AdvancedConfigForTriggerManagedAppDeployInput - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._app_monitoring_config = None
        self._app_storage_config_list = None
        self._custom_labels_and_annotations = None
        self._env_variables = None
        self._health_check = None
        self._service_access_config = None
        self._start_command = None
        self._start_config = None
        self._start_parameter = None
        self.discriminator = None

        if app_monitoring_config is not None:
            self.app_monitoring_config = app_monitoring_config
        if app_storage_config_list is not None:
            self.app_storage_config_list = app_storage_config_list
        if custom_labels_and_annotations is not None:
            self.custom_labels_and_annotations = custom_labels_and_annotations
        if env_variables is not None:
            self.env_variables = env_variables
        if health_check is not None:
            self.health_check = health_check
        if service_access_config is not None:
            self.service_access_config = service_access_config
        if start_command is not None:
            self.start_command = start_command
        if start_config is not None:
            self.start_config = start_config
        if start_parameter is not None:
            self.start_parameter = start_parameter

    @property
    def app_monitoring_config(self):
        """Gets the app_monitoring_config of this AdvancedConfigForTriggerManagedAppDeployInput.  # noqa: E501


        :return: The app_monitoring_config of this AdvancedConfigForTriggerManagedAppDeployInput.  # noqa: E501
        :rtype: AppMonitoringConfigForTriggerManagedAppDeployInput
        """
        return self._app_monitoring_config

    @app_monitoring_config.setter
    def app_monitoring_config(self, app_monitoring_config):
        """Sets the app_monitoring_config of this AdvancedConfigForTriggerManagedAppDeployInput.


        :param app_monitoring_config: The app_monitoring_config of this AdvancedConfigForTriggerManagedAppDeployInput.  # noqa: E501
        :type: AppMonitoringConfigForTriggerManagedAppDeployInput
        """

        self._app_monitoring_config = app_monitoring_config

    @property
    def app_storage_config_list(self):
        """Gets the app_storage_config_list of this AdvancedConfigForTriggerManagedAppDeployInput.  # noqa: E501


        :return: The app_storage_config_list of this AdvancedConfigForTriggerManagedAppDeployInput.  # noqa: E501
        :rtype: list[AppStorageConfigListForTriggerManagedAppDeployInput]
        """
        return self._app_storage_config_list

    @app_storage_config_list.setter
    def app_storage_config_list(self, app_storage_config_list):
        """Sets the app_storage_config_list of this AdvancedConfigForTriggerManagedAppDeployInput.


        :param app_storage_config_list: The app_storage_config_list of this AdvancedConfigForTriggerManagedAppDeployInput.  # noqa: E501
        :type: list[AppStorageConfigListForTriggerManagedAppDeployInput]
        """

        self._app_storage_config_list = app_storage_config_list

    @property
    def custom_labels_and_annotations(self):
        """Gets the custom_labels_and_annotations of this AdvancedConfigForTriggerManagedAppDeployInput.  # noqa: E501


        :return: The custom_labels_and_annotations of this AdvancedConfigForTriggerManagedAppDeployInput.  # noqa: E501
        :rtype: CustomLabelsAndAnnotationsForTriggerManagedAppDeployInput
        """
        return self._custom_labels_and_annotations

    @custom_labels_and_annotations.setter
    def custom_labels_and_annotations(self, custom_labels_and_annotations):
        """Sets the custom_labels_and_annotations of this AdvancedConfigForTriggerManagedAppDeployInput.


        :param custom_labels_and_annotations: The custom_labels_and_annotations of this AdvancedConfigForTriggerManagedAppDeployInput.  # noqa: E501
        :type: CustomLabelsAndAnnotationsForTriggerManagedAppDeployInput
        """

        self._custom_labels_and_annotations = custom_labels_and_annotations

    @property
    def env_variables(self):
        """Gets the env_variables of this AdvancedConfigForTriggerManagedAppDeployInput.  # noqa: E501


        :return: The env_variables of this AdvancedConfigForTriggerManagedAppDeployInput.  # noqa: E501
        :rtype: list[EnvVariableForTriggerManagedAppDeployInput]
        """
        return self._env_variables

    @env_variables.setter
    def env_variables(self, env_variables):
        """Sets the env_variables of this AdvancedConfigForTriggerManagedAppDeployInput.


        :param env_variables: The env_variables of this AdvancedConfigForTriggerManagedAppDeployInput.  # noqa: E501
        :type: list[EnvVariableForTriggerManagedAppDeployInput]
        """

        self._env_variables = env_variables

    @property
    def health_check(self):
        """Gets the health_check of this AdvancedConfigForTriggerManagedAppDeployInput.  # noqa: E501


        :return: The health_check of this AdvancedConfigForTriggerManagedAppDeployInput.  # noqa: E501
        :rtype: HealthCheckForTriggerManagedAppDeployInput
        """
        return self._health_check

    @health_check.setter
    def health_check(self, health_check):
        """Sets the health_check of this AdvancedConfigForTriggerManagedAppDeployInput.


        :param health_check: The health_check of this AdvancedConfigForTriggerManagedAppDeployInput.  # noqa: E501
        :type: HealthCheckForTriggerManagedAppDeployInput
        """

        self._health_check = health_check

    @property
    def service_access_config(self):
        """Gets the service_access_config of this AdvancedConfigForTriggerManagedAppDeployInput.  # noqa: E501


        :return: The service_access_config of this AdvancedConfigForTriggerManagedAppDeployInput.  # noqa: E501
        :rtype: ServiceAccessConfigForTriggerManagedAppDeployInput
        """
        return self._service_access_config

    @service_access_config.setter
    def service_access_config(self, service_access_config):
        """Sets the service_access_config of this AdvancedConfigForTriggerManagedAppDeployInput.


        :param service_access_config: The service_access_config of this AdvancedConfigForTriggerManagedAppDeployInput.  # noqa: E501
        :type: ServiceAccessConfigForTriggerManagedAppDeployInput
        """

        self._service_access_config = service_access_config

    @property
    def start_command(self):
        """Gets the start_command of this AdvancedConfigForTriggerManagedAppDeployInput.  # noqa: E501


        :return: The start_command of this AdvancedConfigForTriggerManagedAppDeployInput.  # noqa: E501
        :rtype: str
        """
        return self._start_command

    @start_command.setter
    def start_command(self, start_command):
        """Sets the start_command of this AdvancedConfigForTriggerManagedAppDeployInput.


        :param start_command: The start_command of this AdvancedConfigForTriggerManagedAppDeployInput.  # noqa: E501
        :type: str
        """

        self._start_command = start_command

    @property
    def start_config(self):
        """Gets the start_config of this AdvancedConfigForTriggerManagedAppDeployInput.  # noqa: E501


        :return: The start_config of this AdvancedConfigForTriggerManagedAppDeployInput.  # noqa: E501
        :rtype: StartConfigForTriggerManagedAppDeployInput
        """
        return self._start_config

    @start_config.setter
    def start_config(self, start_config):
        """Sets the start_config of this AdvancedConfigForTriggerManagedAppDeployInput.


        :param start_config: The start_config of this AdvancedConfigForTriggerManagedAppDeployInput.  # noqa: E501
        :type: StartConfigForTriggerManagedAppDeployInput
        """

        self._start_config = start_config

    @property
    def start_parameter(self):
        """Gets the start_parameter of this AdvancedConfigForTriggerManagedAppDeployInput.  # noqa: E501


        :return: The start_parameter of this AdvancedConfigForTriggerManagedAppDeployInput.  # noqa: E501
        :rtype: str
        """
        return self._start_parameter

    @start_parameter.setter
    def start_parameter(self, start_parameter):
        """Sets the start_parameter of this AdvancedConfigForTriggerManagedAppDeployInput.


        :param start_parameter: The start_parameter of this AdvancedConfigForTriggerManagedAppDeployInput.  # noqa: E501
        :type: str
        """

        self._start_parameter = start_parameter

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AdvancedConfigForTriggerManagedAppDeployInput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdvancedConfigForTriggerManagedAppDeployInput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AdvancedConfigForTriggerManagedAppDeployInput):
            return True

        return self.to_dict() != other.to_dict()
