# coding: utf-8

"""
    cp

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class AppServiceForListManagedAppChangeRecordsOutput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'address_type': 'str',
        'external_traffic_policy': 'str',
        'name': 'str',
        'scheduler': 'str',
        'service_port_mapping': 'list[ServicePortMappingForListManagedAppChangeRecordsOutput]'
    }

    attribute_map = {
        'address_type': 'AddressType',
        'external_traffic_policy': 'ExternalTrafficPolicy',
        'name': 'Name',
        'scheduler': 'Scheduler',
        'service_port_mapping': 'ServicePortMapping'
    }

    def __init__(self, address_type=None, external_traffic_policy=None, name=None, scheduler=None, service_port_mapping=None, _configuration=None):  # noqa: E501
        """AppServiceForListManagedAppChangeRecordsOutput - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._address_type = None
        self._external_traffic_policy = None
        self._name = None
        self._scheduler = None
        self._service_port_mapping = None
        self.discriminator = None

        if address_type is not None:
            self.address_type = address_type
        if external_traffic_policy is not None:
            self.external_traffic_policy = external_traffic_policy
        if name is not None:
            self.name = name
        if scheduler is not None:
            self.scheduler = scheduler
        if service_port_mapping is not None:
            self.service_port_mapping = service_port_mapping

    @property
    def address_type(self):
        """Gets the address_type of this AppServiceForListManagedAppChangeRecordsOutput.  # noqa: E501


        :return: The address_type of this AppServiceForListManagedAppChangeRecordsOutput.  # noqa: E501
        :rtype: str
        """
        return self._address_type

    @address_type.setter
    def address_type(self, address_type):
        """Sets the address_type of this AppServiceForListManagedAppChangeRecordsOutput.


        :param address_type: The address_type of this AppServiceForListManagedAppChangeRecordsOutput.  # noqa: E501
        :type: str
        """

        self._address_type = address_type

    @property
    def external_traffic_policy(self):
        """Gets the external_traffic_policy of this AppServiceForListManagedAppChangeRecordsOutput.  # noqa: E501


        :return: The external_traffic_policy of this AppServiceForListManagedAppChangeRecordsOutput.  # noqa: E501
        :rtype: str
        """
        return self._external_traffic_policy

    @external_traffic_policy.setter
    def external_traffic_policy(self, external_traffic_policy):
        """Sets the external_traffic_policy of this AppServiceForListManagedAppChangeRecordsOutput.


        :param external_traffic_policy: The external_traffic_policy of this AppServiceForListManagedAppChangeRecordsOutput.  # noqa: E501
        :type: str
        """

        self._external_traffic_policy = external_traffic_policy

    @property
    def name(self):
        """Gets the name of this AppServiceForListManagedAppChangeRecordsOutput.  # noqa: E501


        :return: The name of this AppServiceForListManagedAppChangeRecordsOutput.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AppServiceForListManagedAppChangeRecordsOutput.


        :param name: The name of this AppServiceForListManagedAppChangeRecordsOutput.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def scheduler(self):
        """Gets the scheduler of this AppServiceForListManagedAppChangeRecordsOutput.  # noqa: E501


        :return: The scheduler of this AppServiceForListManagedAppChangeRecordsOutput.  # noqa: E501
        :rtype: str
        """
        return self._scheduler

    @scheduler.setter
    def scheduler(self, scheduler):
        """Sets the scheduler of this AppServiceForListManagedAppChangeRecordsOutput.


        :param scheduler: The scheduler of this AppServiceForListManagedAppChangeRecordsOutput.  # noqa: E501
        :type: str
        """

        self._scheduler = scheduler

    @property
    def service_port_mapping(self):
        """Gets the service_port_mapping of this AppServiceForListManagedAppChangeRecordsOutput.  # noqa: E501


        :return: The service_port_mapping of this AppServiceForListManagedAppChangeRecordsOutput.  # noqa: E501
        :rtype: list[ServicePortMappingForListManagedAppChangeRecordsOutput]
        """
        return self._service_port_mapping

    @service_port_mapping.setter
    def service_port_mapping(self, service_port_mapping):
        """Sets the service_port_mapping of this AppServiceForListManagedAppChangeRecordsOutput.


        :param service_port_mapping: The service_port_mapping of this AppServiceForListManagedAppChangeRecordsOutput.  # noqa: E501
        :type: list[ServicePortMappingForListManagedAppChangeRecordsOutput]
        """

        self._service_port_mapping = service_port_mapping

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AppServiceForListManagedAppChangeRecordsOutput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AppServiceForListManagedAppChangeRecordsOutput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AppServiceForListManagedAppChangeRecordsOutput):
            return True

        return self.to_dict() != other.to_dict()
