# coding: utf-8

"""
    id

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class BatchGetOauth2CredentialProvidersRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'names': 'list[str]',
        'pool_name': 'str'
    }

    attribute_map = {
        'names': 'Names',
        'pool_name': 'PoolName'
    }

    def __init__(self, names=None, pool_name=None, _configuration=None):  # noqa: E501
        """BatchGetOauth2CredentialProvidersRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._names = None
        self._pool_name = None
        self.discriminator = None

        if names is not None:
            self.names = names
        if pool_name is not None:
            self.pool_name = pool_name

    @property
    def names(self):
        """Gets the names of this BatchGetOauth2CredentialProvidersRequest.  # noqa: E501


        :return: The names of this BatchGetOauth2CredentialProvidersRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._names

    @names.setter
    def names(self, names):
        """Sets the names of this BatchGetOauth2CredentialProvidersRequest.


        :param names: The names of this BatchGetOauth2CredentialProvidersRequest.  # noqa: E501
        :type: list[str]
        """

        self._names = names

    @property
    def pool_name(self):
        """Gets the pool_name of this BatchGetOauth2CredentialProvidersRequest.  # noqa: E501


        :return: The pool_name of this BatchGetOauth2CredentialProvidersRequest.  # noqa: E501
        :rtype: str
        """
        return self._pool_name

    @pool_name.setter
    def pool_name(self, pool_name):
        """Sets the pool_name of this BatchGetOauth2CredentialProvidersRequest.


        :param pool_name: The pool_name of this BatchGetOauth2CredentialProvidersRequest.  # noqa: E501
        :type: str
        """

        self._pool_name = pool_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BatchGetOauth2CredentialProvidersRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BatchGetOauth2CredentialProvidersRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BatchGetOauth2CredentialProvidersRequest):
            return True

        return self.to_dict() != other.to_dict()
