# coding: utf-8

"""
    id

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class CompleteResourceTokenAuthRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pool_name': 'str',
        'session_uri': 'str',
        'user_identifier': 'UserIdentifierForCompleteResourceTokenAuthInput'
    }

    attribute_map = {
        'pool_name': 'PoolName',
        'session_uri': 'SessionUri',
        'user_identifier': 'UserIdentifier'
    }

    def __init__(self, pool_name=None, session_uri=None, user_identifier=None, _configuration=None):  # noqa: E501
        """CompleteResourceTokenAuthRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._pool_name = None
        self._session_uri = None
        self._user_identifier = None
        self.discriminator = None

        if pool_name is not None:
            self.pool_name = pool_name
        self.session_uri = session_uri
        if user_identifier is not None:
            self.user_identifier = user_identifier

    @property
    def pool_name(self):
        """Gets the pool_name of this CompleteResourceTokenAuthRequest.  # noqa: E501


        :return: The pool_name of this CompleteResourceTokenAuthRequest.  # noqa: E501
        :rtype: str
        """
        return self._pool_name

    @pool_name.setter
    def pool_name(self, pool_name):
        """Sets the pool_name of this CompleteResourceTokenAuthRequest.


        :param pool_name: The pool_name of this CompleteResourceTokenAuthRequest.  # noqa: E501
        :type: str
        """

        self._pool_name = pool_name

    @property
    def session_uri(self):
        """Gets the session_uri of this CompleteResourceTokenAuthRequest.  # noqa: E501


        :return: The session_uri of this CompleteResourceTokenAuthRequest.  # noqa: E501
        :rtype: str
        """
        return self._session_uri

    @session_uri.setter
    def session_uri(self, session_uri):
        """Sets the session_uri of this CompleteResourceTokenAuthRequest.


        :param session_uri: The session_uri of this CompleteResourceTokenAuthRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and session_uri is None:
            raise ValueError("Invalid value for `session_uri`, must not be `None`")  # noqa: E501

        self._session_uri = session_uri

    @property
    def user_identifier(self):
        """Gets the user_identifier of this CompleteResourceTokenAuthRequest.  # noqa: E501


        :return: The user_identifier of this CompleteResourceTokenAuthRequest.  # noqa: E501
        :rtype: UserIdentifierForCompleteResourceTokenAuthInput
        """
        return self._user_identifier

    @user_identifier.setter
    def user_identifier(self, user_identifier):
        """Sets the user_identifier of this CompleteResourceTokenAuthRequest.


        :param user_identifier: The user_identifier of this CompleteResourceTokenAuthRequest.  # noqa: E501
        :type: UserIdentifierForCompleteResourceTokenAuthInput
        """

        self._user_identifier = user_identifier

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CompleteResourceTokenAuthRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CompleteResourceTokenAuthRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CompleteResourceTokenAuthRequest):
            return True

        return self.to_dict() != other.to_dict()
