# coding: utf-8

"""
    vei_api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class FillColorForStopVideoStreamAnalysisTaskOutput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'b': 'int',
        'g': 'int',
        'r': 'int'
    }

    attribute_map = {
        'b': 'b',
        'g': 'g',
        'r': 'r'
    }

    def __init__(self, b=None, g=None, r=None, _configuration=None):  # noqa: E501
        """FillColorForStopVideoStreamAnalysisTaskOutput - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._b = None
        self._g = None
        self._r = None
        self.discriminator = None

        if b is not None:
            self.b = b
        if g is not None:
            self.g = g
        if r is not None:
            self.r = r

    @property
    def b(self):
        """Gets the b of this FillColorForStopVideoStreamAnalysisTaskOutput.  # noqa: E501


        :return: The b of this FillColorForStopVideoStreamAnalysisTaskOutput.  # noqa: E501
        :rtype: int
        """
        return self._b

    @b.setter
    def b(self, b):
        """Sets the b of this FillColorForStopVideoStreamAnalysisTaskOutput.


        :param b: The b of this FillColorForStopVideoStreamAnalysisTaskOutput.  # noqa: E501
        :type: int
        """

        self._b = b

    @property
    def g(self):
        """Gets the g of this FillColorForStopVideoStreamAnalysisTaskOutput.  # noqa: E501


        :return: The g of this FillColorForStopVideoStreamAnalysisTaskOutput.  # noqa: E501
        :rtype: int
        """
        return self._g

    @g.setter
    def g(self, g):
        """Sets the g of this FillColorForStopVideoStreamAnalysisTaskOutput.


        :param g: The g of this FillColorForStopVideoStreamAnalysisTaskOutput.  # noqa: E501
        :type: int
        """

        self._g = g

    @property
    def r(self):
        """Gets the r of this FillColorForStopVideoStreamAnalysisTaskOutput.  # noqa: E501


        :return: The r of this FillColorForStopVideoStreamAnalysisTaskOutput.  # noqa: E501
        :rtype: int
        """
        return self._r

    @r.setter
    def r(self, r):
        """Sets the r of this FillColorForStopVideoStreamAnalysisTaskOutput.


        :param r: The r of this FillColorForStopVideoStreamAnalysisTaskOutput.  # noqa: E501
        :type: int
        """

        self._r = r

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FillColorForStopVideoStreamAnalysisTaskOutput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FillColorForStopVideoStreamAnalysisTaskOutput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FillColorForStopVideoStreamAnalysisTaskOutput):
            return True

        return self.to_dict() != other.to_dict()
