# coding: utf-8

"""
    vefaas_dev

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class ResumeSandboxRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_async': 'bool',
        'function_id': 'str',
        'sandbox_id': 'str',
        'timeout': 'int',
        'timeout_unit': 'str'
    }

    attribute_map = {
        '_async': 'Async',
        'function_id': 'FunctionId',
        'sandbox_id': 'SandboxId',
        'timeout': 'Timeout',
        'timeout_unit': 'TimeoutUnit'
    }

    def __init__(self, _async=None, function_id=None, sandbox_id=None, timeout=None, timeout_unit=None, _configuration=None):  # noqa: E501
        """ResumeSandboxRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self.__async = None
        self._function_id = None
        self._sandbox_id = None
        self._timeout = None
        self._timeout_unit = None
        self.discriminator = None

        if _async is not None:
            self._async = _async
        self.function_id = function_id
        self.sandbox_id = sandbox_id
        if timeout is not None:
            self.timeout = timeout
        if timeout_unit is not None:
            self.timeout_unit = timeout_unit

    @property
    def _async(self):
        """Gets the _async of this ResumeSandboxRequest.  # noqa: E501


        :return: The _async of this ResumeSandboxRequest.  # noqa: E501
        :rtype: bool
        """
        return self.__async

    @_async.setter
    def _async(self, _async):
        """Sets the _async of this ResumeSandboxRequest.


        :param _async: The _async of this ResumeSandboxRequest.  # noqa: E501
        :type: bool
        """

        self.__async = _async

    @property
    def function_id(self):
        """Gets the function_id of this ResumeSandboxRequest.  # noqa: E501


        :return: The function_id of this ResumeSandboxRequest.  # noqa: E501
        :rtype: str
        """
        return self._function_id

    @function_id.setter
    def function_id(self, function_id):
        """Sets the function_id of this ResumeSandboxRequest.


        :param function_id: The function_id of this ResumeSandboxRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and function_id is None:
            raise ValueError("Invalid value for `function_id`, must not be `None`")  # noqa: E501

        self._function_id = function_id

    @property
    def sandbox_id(self):
        """Gets the sandbox_id of this ResumeSandboxRequest.  # noqa: E501


        :return: The sandbox_id of this ResumeSandboxRequest.  # noqa: E501
        :rtype: str
        """
        return self._sandbox_id

    @sandbox_id.setter
    def sandbox_id(self, sandbox_id):
        """Sets the sandbox_id of this ResumeSandboxRequest.


        :param sandbox_id: The sandbox_id of this ResumeSandboxRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and sandbox_id is None:
            raise ValueError("Invalid value for `sandbox_id`, must not be `None`")  # noqa: E501

        self._sandbox_id = sandbox_id

    @property
    def timeout(self):
        """Gets the timeout of this ResumeSandboxRequest.  # noqa: E501


        :return: The timeout of this ResumeSandboxRequest.  # noqa: E501
        :rtype: int
        """
        return self._timeout

    @timeout.setter
    def timeout(self, timeout):
        """Sets the timeout of this ResumeSandboxRequest.


        :param timeout: The timeout of this ResumeSandboxRequest.  # noqa: E501
        :type: int
        """

        self._timeout = timeout

    @property
    def timeout_unit(self):
        """Gets the timeout_unit of this ResumeSandboxRequest.  # noqa: E501


        :return: The timeout_unit of this ResumeSandboxRequest.  # noqa: E501
        :rtype: str
        """
        return self._timeout_unit

    @timeout_unit.setter
    def timeout_unit(self, timeout_unit):
        """Sets the timeout_unit of this ResumeSandboxRequest.


        :param timeout_unit: The timeout_unit of this ResumeSandboxRequest.  # noqa: E501
        :type: str
        """

        self._timeout_unit = timeout_unit

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ResumeSandboxRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResumeSandboxRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ResumeSandboxRequest):
            return True

        return self.to_dict() != other.to_dict()
