# coding: utf-8

"""
    rocketmq

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class ModifyTopicAccessPoliciesRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'access_policies': 'list[AccessPolicyForModifyTopicAccessPoliciesInput]',
        'instance_id': 'str',
        'topic_name': 'str'
    }

    attribute_map = {
        'access_policies': 'AccessPolicies',
        'instance_id': 'InstanceId',
        'topic_name': 'TopicName'
    }

    def __init__(self, access_policies=None, instance_id=None, topic_name=None, _configuration=None):  # noqa: E501
        """ModifyTopicAccessPoliciesRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._access_policies = None
        self._instance_id = None
        self._topic_name = None
        self.discriminator = None

        if access_policies is not None:
            self.access_policies = access_policies
        self.instance_id = instance_id
        self.topic_name = topic_name

    @property
    def access_policies(self):
        """Gets the access_policies of this ModifyTopicAccessPoliciesRequest.  # noqa: E501


        :return: The access_policies of this ModifyTopicAccessPoliciesRequest.  # noqa: E501
        :rtype: list[AccessPolicyForModifyTopicAccessPoliciesInput]
        """
        return self._access_policies

    @access_policies.setter
    def access_policies(self, access_policies):
        """Sets the access_policies of this ModifyTopicAccessPoliciesRequest.


        :param access_policies: The access_policies of this ModifyTopicAccessPoliciesRequest.  # noqa: E501
        :type: list[AccessPolicyForModifyTopicAccessPoliciesInput]
        """

        self._access_policies = access_policies

    @property
    def instance_id(self):
        """Gets the instance_id of this ModifyTopicAccessPoliciesRequest.  # noqa: E501


        :return: The instance_id of this ModifyTopicAccessPoliciesRequest.  # noqa: E501
        :rtype: str
        """
        return self._instance_id

    @instance_id.setter
    def instance_id(self, instance_id):
        """Sets the instance_id of this ModifyTopicAccessPoliciesRequest.


        :param instance_id: The instance_id of this ModifyTopicAccessPoliciesRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and instance_id is None:
            raise ValueError("Invalid value for `instance_id`, must not be `None`")  # noqa: E501

        self._instance_id = instance_id

    @property
    def topic_name(self):
        """Gets the topic_name of this ModifyTopicAccessPoliciesRequest.  # noqa: E501


        :return: The topic_name of this ModifyTopicAccessPoliciesRequest.  # noqa: E501
        :rtype: str
        """
        return self._topic_name

    @topic_name.setter
    def topic_name(self, topic_name):
        """Sets the topic_name of this ModifyTopicAccessPoliciesRequest.


        :param topic_name: The topic_name of this ModifyTopicAccessPoliciesRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and topic_name is None:
            raise ValueError("Invalid value for `topic_name`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                topic_name is not None and len(topic_name) > 64):
            raise ValueError("Invalid value for `topic_name`, length must be less than or equal to `64`")  # noqa: E501
        if (self._configuration.client_side_validation and
                topic_name is not None and len(topic_name) < 3):
            raise ValueError("Invalid value for `topic_name`, length must be greater than or equal to `3`")  # noqa: E501

        self._topic_name = topic_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ModifyTopicAccessPoliciesRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModifyTopicAccessPoliciesRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ModifyTopicAccessPoliciesRequest):
            return True

        return self.to_dict() != other.to_dict()
