# coding: utf-8

"""
    arkclaw

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class UpdateUsersQuotaRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'seat_quota_config': 'SeatQuotaConfigForUpdateUsersQuotaInput',
        'space_id': 'str',
        'uid_list': 'list[str]'
    }

    attribute_map = {
        'seat_quota_config': 'SeatQuotaConfig',
        'space_id': 'SpaceId',
        'uid_list': 'UidList'
    }

    def __init__(self, seat_quota_config=None, space_id=None, uid_list=None, _configuration=None):  # noqa: E501
        """UpdateUsersQuotaRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._seat_quota_config = None
        self._space_id = None
        self._uid_list = None
        self.discriminator = None

        if seat_quota_config is not None:
            self.seat_quota_config = seat_quota_config
        self.space_id = space_id
        if uid_list is not None:
            self.uid_list = uid_list

    @property
    def seat_quota_config(self):
        """Gets the seat_quota_config of this UpdateUsersQuotaRequest.  # noqa: E501


        :return: The seat_quota_config of this UpdateUsersQuotaRequest.  # noqa: E501
        :rtype: SeatQuotaConfigForUpdateUsersQuotaInput
        """
        return self._seat_quota_config

    @seat_quota_config.setter
    def seat_quota_config(self, seat_quota_config):
        """Sets the seat_quota_config of this UpdateUsersQuotaRequest.


        :param seat_quota_config: The seat_quota_config of this UpdateUsersQuotaRequest.  # noqa: E501
        :type: SeatQuotaConfigForUpdateUsersQuotaInput
        """

        self._seat_quota_config = seat_quota_config

    @property
    def space_id(self):
        """Gets the space_id of this UpdateUsersQuotaRequest.  # noqa: E501


        :return: The space_id of this UpdateUsersQuotaRequest.  # noqa: E501
        :rtype: str
        """
        return self._space_id

    @space_id.setter
    def space_id(self, space_id):
        """Sets the space_id of this UpdateUsersQuotaRequest.


        :param space_id: The space_id of this UpdateUsersQuotaRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and space_id is None:
            raise ValueError("Invalid value for `space_id`, must not be `None`")  # noqa: E501

        self._space_id = space_id

    @property
    def uid_list(self):
        """Gets the uid_list of this UpdateUsersQuotaRequest.  # noqa: E501


        :return: The uid_list of this UpdateUsersQuotaRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._uid_list

    @uid_list.setter
    def uid_list(self, uid_list):
        """Sets the uid_list of this UpdateUsersQuotaRequest.


        :param uid_list: The uid_list of this UpdateUsersQuotaRequest.  # noqa: E501
        :type: list[str]
        """

        self._uid_list = uid_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateUsersQuotaRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateUsersQuotaRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UpdateUsersQuotaRequest):
            return True

        return self.to_dict() != other.to_dict()
