# coding: utf-8

"""
    cdn

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class DescribeCdnRegionAndIspResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'isps': 'list[IspForDescribeCdnRegionAndIspOutput]',
        'regions': 'list[RegionForDescribeCdnRegionAndIspOutput]'
    }

    attribute_map = {
        'isps': 'Isps',
        'regions': 'Regions'
    }

    def __init__(self, isps=None, regions=None, _configuration=None):  # noqa: E501
        """DescribeCdnRegionAndIspResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._isps = None
        self._regions = None
        self.discriminator = None

        if isps is not None:
            self.isps = isps
        if regions is not None:
            self.regions = regions

    @property
    def isps(self):
        """Gets the isps of this DescribeCdnRegionAndIspResponse.  # noqa: E501


        :return: The isps of this DescribeCdnRegionAndIspResponse.  # noqa: E501
        :rtype: list[IspForDescribeCdnRegionAndIspOutput]
        """
        return self._isps

    @isps.setter
    def isps(self, isps):
        """Sets the isps of this DescribeCdnRegionAndIspResponse.


        :param isps: The isps of this DescribeCdnRegionAndIspResponse.  # noqa: E501
        :type: list[IspForDescribeCdnRegionAndIspOutput]
        """

        self._isps = isps

    @property
    def regions(self):
        """Gets the regions of this DescribeCdnRegionAndIspResponse.  # noqa: E501


        :return: The regions of this DescribeCdnRegionAndIspResponse.  # noqa: E501
        :rtype: list[RegionForDescribeCdnRegionAndIspOutput]
        """
        return self._regions

    @regions.setter
    def regions(self, regions):
        """Sets the regions of this DescribeCdnRegionAndIspResponse.


        :param regions: The regions of this DescribeCdnRegionAndIspResponse.  # noqa: E501
        :type: list[RegionForDescribeCdnRegionAndIspOutput]
        """

        self._regions = regions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DescribeCdnRegionAndIspResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DescribeCdnRegionAndIspResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DescribeCdnRegionAndIspResponse):
            return True

        return self.to_dict() != other.to_dict()
