# coding: utf-8

# flake8: noqa

"""
    nta

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from volcenginesdknta.api.nta_api import NTAApi

# import models into sdk package
from volcenginesdknta.models.create_file_detection_request import CreateFileDetectionRequest
from volcenginesdknta.models.create_file_detection_response import CreateFileDetectionResponse
from volcenginesdknta.models.get_file_detection_request import GetFileDetectionRequest
from volcenginesdknta.models.get_file_detection_response import GetFileDetectionResponse
