# coding: utf-8

"""
    config

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class DescribeAccountGroupDeliveryChannelResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'account_group_id': 'str',
        'condition': 'str',
        'created_time': 'str',
        'delivery_channel_id': 'str',
        'delivery_channel_name': 'str',
        'delivery_channel_target_trn': 'str',
        'delivery_channel_type': 'str',
        'delivery_contents': 'list[str]',
        'delivery_role_trn': 'str',
        'snapshot_delivery_time': 'str',
        'status': 'str',
        'tos_key_prefix': 'str',
        'tos_sse_algorithm': 'str',
        'tos_ssekms_key_id': 'str',
        'updated_time': 'str'
    }

    attribute_map = {
        'account_group_id': 'AccountGroupId',
        'condition': 'Condition',
        'created_time': 'CreatedTime',
        'delivery_channel_id': 'DeliveryChannelId',
        'delivery_channel_name': 'DeliveryChannelName',
        'delivery_channel_target_trn': 'DeliveryChannelTargetTrn',
        'delivery_channel_type': 'DeliveryChannelType',
        'delivery_contents': 'DeliveryContents',
        'delivery_role_trn': 'DeliveryRoleTrn',
        'snapshot_delivery_time': 'SnapshotDeliveryTime',
        'status': 'Status',
        'tos_key_prefix': 'TosKeyPrefix',
        'tos_sse_algorithm': 'TosSSEAlgorithm',
        'tos_ssekms_key_id': 'TosSSEKMSKeyId',
        'updated_time': 'UpdatedTime'
    }

    def __init__(self, account_group_id=None, condition=None, created_time=None, delivery_channel_id=None, delivery_channel_name=None, delivery_channel_target_trn=None, delivery_channel_type=None, delivery_contents=None, delivery_role_trn=None, snapshot_delivery_time=None, status=None, tos_key_prefix=None, tos_sse_algorithm=None, tos_ssekms_key_id=None, updated_time=None, _configuration=None):  # noqa: E501
        """DescribeAccountGroupDeliveryChannelResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._account_group_id = None
        self._condition = None
        self._created_time = None
        self._delivery_channel_id = None
        self._delivery_channel_name = None
        self._delivery_channel_target_trn = None
        self._delivery_channel_type = None
        self._delivery_contents = None
        self._delivery_role_trn = None
        self._snapshot_delivery_time = None
        self._status = None
        self._tos_key_prefix = None
        self._tos_sse_algorithm = None
        self._tos_ssekms_key_id = None
        self._updated_time = None
        self.discriminator = None

        if account_group_id is not None:
            self.account_group_id = account_group_id
        if condition is not None:
            self.condition = condition
        if created_time is not None:
            self.created_time = created_time
        if delivery_channel_id is not None:
            self.delivery_channel_id = delivery_channel_id
        if delivery_channel_name is not None:
            self.delivery_channel_name = delivery_channel_name
        if delivery_channel_target_trn is not None:
            self.delivery_channel_target_trn = delivery_channel_target_trn
        if delivery_channel_type is not None:
            self.delivery_channel_type = delivery_channel_type
        if delivery_contents is not None:
            self.delivery_contents = delivery_contents
        if delivery_role_trn is not None:
            self.delivery_role_trn = delivery_role_trn
        if snapshot_delivery_time is not None:
            self.snapshot_delivery_time = snapshot_delivery_time
        if status is not None:
            self.status = status
        if tos_key_prefix is not None:
            self.tos_key_prefix = tos_key_prefix
        if tos_sse_algorithm is not None:
            self.tos_sse_algorithm = tos_sse_algorithm
        if tos_ssekms_key_id is not None:
            self.tos_ssekms_key_id = tos_ssekms_key_id
        if updated_time is not None:
            self.updated_time = updated_time

    @property
    def account_group_id(self):
        """Gets the account_group_id of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501


        :return: The account_group_id of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :rtype: str
        """
        return self._account_group_id

    @account_group_id.setter
    def account_group_id(self, account_group_id):
        """Sets the account_group_id of this DescribeAccountGroupDeliveryChannelResponse.


        :param account_group_id: The account_group_id of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :type: str
        """

        self._account_group_id = account_group_id

    @property
    def condition(self):
        """Gets the condition of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501


        :return: The condition of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :rtype: str
        """
        return self._condition

    @condition.setter
    def condition(self, condition):
        """Sets the condition of this DescribeAccountGroupDeliveryChannelResponse.


        :param condition: The condition of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :type: str
        """

        self._condition = condition

    @property
    def created_time(self):
        """Gets the created_time of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501


        :return: The created_time of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :rtype: str
        """
        return self._created_time

    @created_time.setter
    def created_time(self, created_time):
        """Sets the created_time of this DescribeAccountGroupDeliveryChannelResponse.


        :param created_time: The created_time of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :type: str
        """

        self._created_time = created_time

    @property
    def delivery_channel_id(self):
        """Gets the delivery_channel_id of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501


        :return: The delivery_channel_id of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :rtype: str
        """
        return self._delivery_channel_id

    @delivery_channel_id.setter
    def delivery_channel_id(self, delivery_channel_id):
        """Sets the delivery_channel_id of this DescribeAccountGroupDeliveryChannelResponse.


        :param delivery_channel_id: The delivery_channel_id of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :type: str
        """

        self._delivery_channel_id = delivery_channel_id

    @property
    def delivery_channel_name(self):
        """Gets the delivery_channel_name of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501


        :return: The delivery_channel_name of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :rtype: str
        """
        return self._delivery_channel_name

    @delivery_channel_name.setter
    def delivery_channel_name(self, delivery_channel_name):
        """Sets the delivery_channel_name of this DescribeAccountGroupDeliveryChannelResponse.


        :param delivery_channel_name: The delivery_channel_name of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :type: str
        """

        self._delivery_channel_name = delivery_channel_name

    @property
    def delivery_channel_target_trn(self):
        """Gets the delivery_channel_target_trn of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501


        :return: The delivery_channel_target_trn of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :rtype: str
        """
        return self._delivery_channel_target_trn

    @delivery_channel_target_trn.setter
    def delivery_channel_target_trn(self, delivery_channel_target_trn):
        """Sets the delivery_channel_target_trn of this DescribeAccountGroupDeliveryChannelResponse.


        :param delivery_channel_target_trn: The delivery_channel_target_trn of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :type: str
        """

        self._delivery_channel_target_trn = delivery_channel_target_trn

    @property
    def delivery_channel_type(self):
        """Gets the delivery_channel_type of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501


        :return: The delivery_channel_type of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :rtype: str
        """
        return self._delivery_channel_type

    @delivery_channel_type.setter
    def delivery_channel_type(self, delivery_channel_type):
        """Sets the delivery_channel_type of this DescribeAccountGroupDeliveryChannelResponse.


        :param delivery_channel_type: The delivery_channel_type of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :type: str
        """

        self._delivery_channel_type = delivery_channel_type

    @property
    def delivery_contents(self):
        """Gets the delivery_contents of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501


        :return: The delivery_contents of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._delivery_contents

    @delivery_contents.setter
    def delivery_contents(self, delivery_contents):
        """Sets the delivery_contents of this DescribeAccountGroupDeliveryChannelResponse.


        :param delivery_contents: The delivery_contents of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :type: list[str]
        """

        self._delivery_contents = delivery_contents

    @property
    def delivery_role_trn(self):
        """Gets the delivery_role_trn of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501


        :return: The delivery_role_trn of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :rtype: str
        """
        return self._delivery_role_trn

    @delivery_role_trn.setter
    def delivery_role_trn(self, delivery_role_trn):
        """Sets the delivery_role_trn of this DescribeAccountGroupDeliveryChannelResponse.


        :param delivery_role_trn: The delivery_role_trn of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :type: str
        """

        self._delivery_role_trn = delivery_role_trn

    @property
    def snapshot_delivery_time(self):
        """Gets the snapshot_delivery_time of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501


        :return: The snapshot_delivery_time of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :rtype: str
        """
        return self._snapshot_delivery_time

    @snapshot_delivery_time.setter
    def snapshot_delivery_time(self, snapshot_delivery_time):
        """Sets the snapshot_delivery_time of this DescribeAccountGroupDeliveryChannelResponse.


        :param snapshot_delivery_time: The snapshot_delivery_time of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :type: str
        """

        self._snapshot_delivery_time = snapshot_delivery_time

    @property
    def status(self):
        """Gets the status of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501


        :return: The status of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this DescribeAccountGroupDeliveryChannelResponse.


        :param status: The status of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def tos_key_prefix(self):
        """Gets the tos_key_prefix of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501


        :return: The tos_key_prefix of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :rtype: str
        """
        return self._tos_key_prefix

    @tos_key_prefix.setter
    def tos_key_prefix(self, tos_key_prefix):
        """Sets the tos_key_prefix of this DescribeAccountGroupDeliveryChannelResponse.


        :param tos_key_prefix: The tos_key_prefix of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :type: str
        """

        self._tos_key_prefix = tos_key_prefix

    @property
    def tos_sse_algorithm(self):
        """Gets the tos_sse_algorithm of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501


        :return: The tos_sse_algorithm of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :rtype: str
        """
        return self._tos_sse_algorithm

    @tos_sse_algorithm.setter
    def tos_sse_algorithm(self, tos_sse_algorithm):
        """Sets the tos_sse_algorithm of this DescribeAccountGroupDeliveryChannelResponse.


        :param tos_sse_algorithm: The tos_sse_algorithm of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :type: str
        """

        self._tos_sse_algorithm = tos_sse_algorithm

    @property
    def tos_ssekms_key_id(self):
        """Gets the tos_ssekms_key_id of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501


        :return: The tos_ssekms_key_id of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :rtype: str
        """
        return self._tos_ssekms_key_id

    @tos_ssekms_key_id.setter
    def tos_ssekms_key_id(self, tos_ssekms_key_id):
        """Sets the tos_ssekms_key_id of this DescribeAccountGroupDeliveryChannelResponse.


        :param tos_ssekms_key_id: The tos_ssekms_key_id of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :type: str
        """

        self._tos_ssekms_key_id = tos_ssekms_key_id

    @property
    def updated_time(self):
        """Gets the updated_time of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501


        :return: The updated_time of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :rtype: str
        """
        return self._updated_time

    @updated_time.setter
    def updated_time(self, updated_time):
        """Sets the updated_time of this DescribeAccountGroupDeliveryChannelResponse.


        :param updated_time: The updated_time of this DescribeAccountGroupDeliveryChannelResponse.  # noqa: E501
        :type: str
        """

        self._updated_time = updated_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DescribeAccountGroupDeliveryChannelResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DescribeAccountGroupDeliveryChannelResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DescribeAccountGroupDeliveryChannelResponse):
            return True

        return self.to_dict() != other.to_dict()
