# coding: utf-8

"""
    fwcenter

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class CreateFwInstanceForUserRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bandwidth_cap': 'int',
        'combo': 'int',
        'dns_cap': 'int',
        'elastic_traffic_extend_flag': 'int',
        'is_auto_renew': 'int',
        'nat_bandwidth_cap': 'int',
        'nat_instance_cap': 'int',
        'order_type': 'int',
        'policy_cap': 'int',
        'product': 'int',
        'project_name': 'str',
        'sec_intelligent_flag': 'int',
        'tags': 'list[TagForCreateFwInstanceForUserInput]',
        'times': 'int',
        'tls_log_cap': 'int',
        'tls_log_storage_flag': 'int',
        'tls_region': 'str',
        'vpc_bandwidth_cap': 'int',
        'vpc_instance_cap': 'int'
    }

    attribute_map = {
        'bandwidth_cap': 'BandwidthCap',
        'combo': 'Combo',
        'dns_cap': 'DnsCap',
        'elastic_traffic_extend_flag': 'ElasticTrafficExtendFlag',
        'is_auto_renew': 'IsAutoRenew',
        'nat_bandwidth_cap': 'NatBandwidthCap',
        'nat_instance_cap': 'NatInstanceCap',
        'order_type': 'OrderType',
        'policy_cap': 'PolicyCap',
        'product': 'Product',
        'project_name': 'ProjectName',
        'sec_intelligent_flag': 'SecIntelligentFlag',
        'tags': 'Tags',
        'times': 'Times',
        'tls_log_cap': 'TlsLogCap',
        'tls_log_storage_flag': 'TlsLogStorageFlag',
        'tls_region': 'TlsRegion',
        'vpc_bandwidth_cap': 'VpcBandwidthCap',
        'vpc_instance_cap': 'VpcInstanceCap'
    }

    def __init__(self, bandwidth_cap=None, combo=None, dns_cap=None, elastic_traffic_extend_flag=None, is_auto_renew=None, nat_bandwidth_cap=None, nat_instance_cap=None, order_type=None, policy_cap=None, product=None, project_name=None, sec_intelligent_flag=None, tags=None, times=None, tls_log_cap=None, tls_log_storage_flag=None, tls_region=None, vpc_bandwidth_cap=None, vpc_instance_cap=None, _configuration=None):  # noqa: E501
        """CreateFwInstanceForUserRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._bandwidth_cap = None
        self._combo = None
        self._dns_cap = None
        self._elastic_traffic_extend_flag = None
        self._is_auto_renew = None
        self._nat_bandwidth_cap = None
        self._nat_instance_cap = None
        self._order_type = None
        self._policy_cap = None
        self._product = None
        self._project_name = None
        self._sec_intelligent_flag = None
        self._tags = None
        self._times = None
        self._tls_log_cap = None
        self._tls_log_storage_flag = None
        self._tls_region = None
        self._vpc_bandwidth_cap = None
        self._vpc_instance_cap = None
        self.discriminator = None

        if bandwidth_cap is not None:
            self.bandwidth_cap = bandwidth_cap
        self.combo = combo
        if dns_cap is not None:
            self.dns_cap = dns_cap
        if elastic_traffic_extend_flag is not None:
            self.elastic_traffic_extend_flag = elastic_traffic_extend_flag
        if is_auto_renew is not None:
            self.is_auto_renew = is_auto_renew
        if nat_bandwidth_cap is not None:
            self.nat_bandwidth_cap = nat_bandwidth_cap
        if nat_instance_cap is not None:
            self.nat_instance_cap = nat_instance_cap
        self.order_type = order_type
        if policy_cap is not None:
            self.policy_cap = policy_cap
        if product is not None:
            self.product = product
        if project_name is not None:
            self.project_name = project_name
        if sec_intelligent_flag is not None:
            self.sec_intelligent_flag = sec_intelligent_flag
        if tags is not None:
            self.tags = tags
        if times is not None:
            self.times = times
        if tls_log_cap is not None:
            self.tls_log_cap = tls_log_cap
        if tls_log_storage_flag is not None:
            self.tls_log_storage_flag = tls_log_storage_flag
        if tls_region is not None:
            self.tls_region = tls_region
        if vpc_bandwidth_cap is not None:
            self.vpc_bandwidth_cap = vpc_bandwidth_cap
        if vpc_instance_cap is not None:
            self.vpc_instance_cap = vpc_instance_cap

    @property
    def bandwidth_cap(self):
        """Gets the bandwidth_cap of this CreateFwInstanceForUserRequest.  # noqa: E501


        :return: The bandwidth_cap of this CreateFwInstanceForUserRequest.  # noqa: E501
        :rtype: int
        """
        return self._bandwidth_cap

    @bandwidth_cap.setter
    def bandwidth_cap(self, bandwidth_cap):
        """Sets the bandwidth_cap of this CreateFwInstanceForUserRequest.


        :param bandwidth_cap: The bandwidth_cap of this CreateFwInstanceForUserRequest.  # noqa: E501
        :type: int
        """
        if (self._configuration.client_side_validation and
                bandwidth_cap is not None and bandwidth_cap > 100000):  # noqa: E501
            raise ValueError("Invalid value for `bandwidth_cap`, must be a value less than or equal to `100000`")  # noqa: E501
        if (self._configuration.client_side_validation and
                bandwidth_cap is not None and bandwidth_cap < 0):  # noqa: E501
            raise ValueError("Invalid value for `bandwidth_cap`, must be a value greater than or equal to `0`")  # noqa: E501

        self._bandwidth_cap = bandwidth_cap

    @property
    def combo(self):
        """Gets the combo of this CreateFwInstanceForUserRequest.  # noqa: E501


        :return: The combo of this CreateFwInstanceForUserRequest.  # noqa: E501
        :rtype: int
        """
        return self._combo

    @combo.setter
    def combo(self, combo):
        """Sets the combo of this CreateFwInstanceForUserRequest.


        :param combo: The combo of this CreateFwInstanceForUserRequest.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and combo is None:
            raise ValueError("Invalid value for `combo`, must not be `None`")  # noqa: E501

        self._combo = combo

    @property
    def dns_cap(self):
        """Gets the dns_cap of this CreateFwInstanceForUserRequest.  # noqa: E501


        :return: The dns_cap of this CreateFwInstanceForUserRequest.  # noqa: E501
        :rtype: int
        """
        return self._dns_cap

    @dns_cap.setter
    def dns_cap(self, dns_cap):
        """Sets the dns_cap of this CreateFwInstanceForUserRequest.


        :param dns_cap: The dns_cap of this CreateFwInstanceForUserRequest.  # noqa: E501
        :type: int
        """
        if (self._configuration.client_side_validation and
                dns_cap is not None and dns_cap > 50000):  # noqa: E501
            raise ValueError("Invalid value for `dns_cap`, must be a value less than or equal to `50000`")  # noqa: E501
        if (self._configuration.client_side_validation and
                dns_cap is not None and dns_cap < 0):  # noqa: E501
            raise ValueError("Invalid value for `dns_cap`, must be a value greater than or equal to `0`")  # noqa: E501

        self._dns_cap = dns_cap

    @property
    def elastic_traffic_extend_flag(self):
        """Gets the elastic_traffic_extend_flag of this CreateFwInstanceForUserRequest.  # noqa: E501


        :return: The elastic_traffic_extend_flag of this CreateFwInstanceForUserRequest.  # noqa: E501
        :rtype: int
        """
        return self._elastic_traffic_extend_flag

    @elastic_traffic_extend_flag.setter
    def elastic_traffic_extend_flag(self, elastic_traffic_extend_flag):
        """Sets the elastic_traffic_extend_flag of this CreateFwInstanceForUserRequest.


        :param elastic_traffic_extend_flag: The elastic_traffic_extend_flag of this CreateFwInstanceForUserRequest.  # noqa: E501
        :type: int
        """

        self._elastic_traffic_extend_flag = elastic_traffic_extend_flag

    @property
    def is_auto_renew(self):
        """Gets the is_auto_renew of this CreateFwInstanceForUserRequest.  # noqa: E501


        :return: The is_auto_renew of this CreateFwInstanceForUserRequest.  # noqa: E501
        :rtype: int
        """
        return self._is_auto_renew

    @is_auto_renew.setter
    def is_auto_renew(self, is_auto_renew):
        """Sets the is_auto_renew of this CreateFwInstanceForUserRequest.


        :param is_auto_renew: The is_auto_renew of this CreateFwInstanceForUserRequest.  # noqa: E501
        :type: int
        """

        self._is_auto_renew = is_auto_renew

    @property
    def nat_bandwidth_cap(self):
        """Gets the nat_bandwidth_cap of this CreateFwInstanceForUserRequest.  # noqa: E501


        :return: The nat_bandwidth_cap of this CreateFwInstanceForUserRequest.  # noqa: E501
        :rtype: int
        """
        return self._nat_bandwidth_cap

    @nat_bandwidth_cap.setter
    def nat_bandwidth_cap(self, nat_bandwidth_cap):
        """Sets the nat_bandwidth_cap of this CreateFwInstanceForUserRequest.


        :param nat_bandwidth_cap: The nat_bandwidth_cap of this CreateFwInstanceForUserRequest.  # noqa: E501
        :type: int
        """
        if (self._configuration.client_side_validation and
                nat_bandwidth_cap is not None and nat_bandwidth_cap > 10000):  # noqa: E501
            raise ValueError("Invalid value for `nat_bandwidth_cap`, must be a value less than or equal to `10000`")  # noqa: E501
        if (self._configuration.client_side_validation and
                nat_bandwidth_cap is not None and nat_bandwidth_cap < 0):  # noqa: E501
            raise ValueError("Invalid value for `nat_bandwidth_cap`, must be a value greater than or equal to `0`")  # noqa: E501

        self._nat_bandwidth_cap = nat_bandwidth_cap

    @property
    def nat_instance_cap(self):
        """Gets the nat_instance_cap of this CreateFwInstanceForUserRequest.  # noqa: E501


        :return: The nat_instance_cap of this CreateFwInstanceForUserRequest.  # noqa: E501
        :rtype: int
        """
        return self._nat_instance_cap

    @nat_instance_cap.setter
    def nat_instance_cap(self, nat_instance_cap):
        """Sets the nat_instance_cap of this CreateFwInstanceForUserRequest.


        :param nat_instance_cap: The nat_instance_cap of this CreateFwInstanceForUserRequest.  # noqa: E501
        :type: int
        """
        if (self._configuration.client_side_validation and
                nat_instance_cap is not None and nat_instance_cap > 200):  # noqa: E501
            raise ValueError("Invalid value for `nat_instance_cap`, must be a value less than or equal to `200`")  # noqa: E501
        if (self._configuration.client_side_validation and
                nat_instance_cap is not None and nat_instance_cap < 0):  # noqa: E501
            raise ValueError("Invalid value for `nat_instance_cap`, must be a value greater than or equal to `0`")  # noqa: E501

        self._nat_instance_cap = nat_instance_cap

    @property
    def order_type(self):
        """Gets the order_type of this CreateFwInstanceForUserRequest.  # noqa: E501


        :return: The order_type of this CreateFwInstanceForUserRequest.  # noqa: E501
        :rtype: int
        """
        return self._order_type

    @order_type.setter
    def order_type(self, order_type):
        """Sets the order_type of this CreateFwInstanceForUserRequest.


        :param order_type: The order_type of this CreateFwInstanceForUserRequest.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and order_type is None:
            raise ValueError("Invalid value for `order_type`, must not be `None`")  # noqa: E501

        self._order_type = order_type

    @property
    def policy_cap(self):
        """Gets the policy_cap of this CreateFwInstanceForUserRequest.  # noqa: E501


        :return: The policy_cap of this CreateFwInstanceForUserRequest.  # noqa: E501
        :rtype: int
        """
        return self._policy_cap

    @policy_cap.setter
    def policy_cap(self, policy_cap):
        """Sets the policy_cap of this CreateFwInstanceForUserRequest.


        :param policy_cap: The policy_cap of this CreateFwInstanceForUserRequest.  # noqa: E501
        :type: int
        """
        if (self._configuration.client_side_validation and
                policy_cap is not None and policy_cap > 300000):  # noqa: E501
            raise ValueError("Invalid value for `policy_cap`, must be a value less than or equal to `300000`")  # noqa: E501
        if (self._configuration.client_side_validation and
                policy_cap is not None and policy_cap < 0):  # noqa: E501
            raise ValueError("Invalid value for `policy_cap`, must be a value greater than or equal to `0`")  # noqa: E501

        self._policy_cap = policy_cap

    @property
    def product(self):
        """Gets the product of this CreateFwInstanceForUserRequest.  # noqa: E501


        :return: The product of this CreateFwInstanceForUserRequest.  # noqa: E501
        :rtype: int
        """
        return self._product

    @product.setter
    def product(self, product):
        """Sets the product of this CreateFwInstanceForUserRequest.


        :param product: The product of this CreateFwInstanceForUserRequest.  # noqa: E501
        :type: int
        """

        self._product = product

    @property
    def project_name(self):
        """Gets the project_name of this CreateFwInstanceForUserRequest.  # noqa: E501


        :return: The project_name of this CreateFwInstanceForUserRequest.  # noqa: E501
        :rtype: str
        """
        return self._project_name

    @project_name.setter
    def project_name(self, project_name):
        """Sets the project_name of this CreateFwInstanceForUserRequest.


        :param project_name: The project_name of this CreateFwInstanceForUserRequest.  # noqa: E501
        :type: str
        """

        self._project_name = project_name

    @property
    def sec_intelligent_flag(self):
        """Gets the sec_intelligent_flag of this CreateFwInstanceForUserRequest.  # noqa: E501


        :return: The sec_intelligent_flag of this CreateFwInstanceForUserRequest.  # noqa: E501
        :rtype: int
        """
        return self._sec_intelligent_flag

    @sec_intelligent_flag.setter
    def sec_intelligent_flag(self, sec_intelligent_flag):
        """Sets the sec_intelligent_flag of this CreateFwInstanceForUserRequest.


        :param sec_intelligent_flag: The sec_intelligent_flag of this CreateFwInstanceForUserRequest.  # noqa: E501
        :type: int
        """

        self._sec_intelligent_flag = sec_intelligent_flag

    @property
    def tags(self):
        """Gets the tags of this CreateFwInstanceForUserRequest.  # noqa: E501


        :return: The tags of this CreateFwInstanceForUserRequest.  # noqa: E501
        :rtype: list[TagForCreateFwInstanceForUserInput]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this CreateFwInstanceForUserRequest.


        :param tags: The tags of this CreateFwInstanceForUserRequest.  # noqa: E501
        :type: list[TagForCreateFwInstanceForUserInput]
        """

        self._tags = tags

    @property
    def times(self):
        """Gets the times of this CreateFwInstanceForUserRequest.  # noqa: E501


        :return: The times of this CreateFwInstanceForUserRequest.  # noqa: E501
        :rtype: int
        """
        return self._times

    @times.setter
    def times(self, times):
        """Sets the times of this CreateFwInstanceForUserRequest.


        :param times: The times of this CreateFwInstanceForUserRequest.  # noqa: E501
        :type: int
        """
        if (self._configuration.client_side_validation and
                times is not None and times > 36):  # noqa: E501
            raise ValueError("Invalid value for `times`, must be a value less than or equal to `36`")  # noqa: E501
        if (self._configuration.client_side_validation and
                times is not None and times < 1):  # noqa: E501
            raise ValueError("Invalid value for `times`, must be a value greater than or equal to `1`")  # noqa: E501

        self._times = times

    @property
    def tls_log_cap(self):
        """Gets the tls_log_cap of this CreateFwInstanceForUserRequest.  # noqa: E501


        :return: The tls_log_cap of this CreateFwInstanceForUserRequest.  # noqa: E501
        :rtype: int
        """
        return self._tls_log_cap

    @tls_log_cap.setter
    def tls_log_cap(self, tls_log_cap):
        """Sets the tls_log_cap of this CreateFwInstanceForUserRequest.


        :param tls_log_cap: The tls_log_cap of this CreateFwInstanceForUserRequest.  # noqa: E501
        :type: int
        """
        if (self._configuration.client_side_validation and
                tls_log_cap is not None and tls_log_cap > 500):  # noqa: E501
            raise ValueError("Invalid value for `tls_log_cap`, must be a value less than or equal to `500`")  # noqa: E501
        if (self._configuration.client_side_validation and
                tls_log_cap is not None and tls_log_cap < 0):  # noqa: E501
            raise ValueError("Invalid value for `tls_log_cap`, must be a value greater than or equal to `0`")  # noqa: E501

        self._tls_log_cap = tls_log_cap

    @property
    def tls_log_storage_flag(self):
        """Gets the tls_log_storage_flag of this CreateFwInstanceForUserRequest.  # noqa: E501


        :return: The tls_log_storage_flag of this CreateFwInstanceForUserRequest.  # noqa: E501
        :rtype: int
        """
        return self._tls_log_storage_flag

    @tls_log_storage_flag.setter
    def tls_log_storage_flag(self, tls_log_storage_flag):
        """Sets the tls_log_storage_flag of this CreateFwInstanceForUserRequest.


        :param tls_log_storage_flag: The tls_log_storage_flag of this CreateFwInstanceForUserRequest.  # noqa: E501
        :type: int
        """

        self._tls_log_storage_flag = tls_log_storage_flag

    @property
    def tls_region(self):
        """Gets the tls_region of this CreateFwInstanceForUserRequest.  # noqa: E501


        :return: The tls_region of this CreateFwInstanceForUserRequest.  # noqa: E501
        :rtype: str
        """
        return self._tls_region

    @tls_region.setter
    def tls_region(self, tls_region):
        """Sets the tls_region of this CreateFwInstanceForUserRequest.


        :param tls_region: The tls_region of this CreateFwInstanceForUserRequest.  # noqa: E501
        :type: str
        """

        self._tls_region = tls_region

    @property
    def vpc_bandwidth_cap(self):
        """Gets the vpc_bandwidth_cap of this CreateFwInstanceForUserRequest.  # noqa: E501


        :return: The vpc_bandwidth_cap of this CreateFwInstanceForUserRequest.  # noqa: E501
        :rtype: int
        """
        return self._vpc_bandwidth_cap

    @vpc_bandwidth_cap.setter
    def vpc_bandwidth_cap(self, vpc_bandwidth_cap):
        """Sets the vpc_bandwidth_cap of this CreateFwInstanceForUserRequest.


        :param vpc_bandwidth_cap: The vpc_bandwidth_cap of this CreateFwInstanceForUserRequest.  # noqa: E501
        :type: int
        """
        if (self._configuration.client_side_validation and
                vpc_bandwidth_cap is not None and vpc_bandwidth_cap > 2000000):  # noqa: E501
            raise ValueError("Invalid value for `vpc_bandwidth_cap`, must be a value less than or equal to `2000000`")  # noqa: E501
        if (self._configuration.client_side_validation and
                vpc_bandwidth_cap is not None and vpc_bandwidth_cap < 0):  # noqa: E501
            raise ValueError("Invalid value for `vpc_bandwidth_cap`, must be a value greater than or equal to `0`")  # noqa: E501

        self._vpc_bandwidth_cap = vpc_bandwidth_cap

    @property
    def vpc_instance_cap(self):
        """Gets the vpc_instance_cap of this CreateFwInstanceForUserRequest.  # noqa: E501


        :return: The vpc_instance_cap of this CreateFwInstanceForUserRequest.  # noqa: E501
        :rtype: int
        """
        return self._vpc_instance_cap

    @vpc_instance_cap.setter
    def vpc_instance_cap(self, vpc_instance_cap):
        """Sets the vpc_instance_cap of this CreateFwInstanceForUserRequest.


        :param vpc_instance_cap: The vpc_instance_cap of this CreateFwInstanceForUserRequest.  # noqa: E501
        :type: int
        """
        if (self._configuration.client_side_validation and
                vpc_instance_cap is not None and vpc_instance_cap > 200):  # noqa: E501
            raise ValueError("Invalid value for `vpc_instance_cap`, must be a value less than or equal to `200`")  # noqa: E501
        if (self._configuration.client_side_validation and
                vpc_instance_cap is not None and vpc_instance_cap < 0):  # noqa: E501
            raise ValueError("Invalid value for `vpc_instance_cap`, must be a value greater than or equal to `0`")  # noqa: E501

        self._vpc_instance_cap = vpc_instance_cap

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateFwInstanceForUserRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateFwInstanceForUserRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateFwInstanceForUserRequest):
            return True

        return self.to_dict() != other.to_dict()
