# coding: utf-8

"""
    vod20250101

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class TermItemForListAITermbaseOutput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'source_text': 'str',
        'target_text': 'str'
    }

    attribute_map = {
        'source_text': 'SourceText',
        'target_text': 'TargetText'
    }

    def __init__(self, source_text=None, target_text=None, _configuration=None):  # noqa: E501
        """TermItemForListAITermbaseOutput - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._source_text = None
        self._target_text = None
        self.discriminator = None

        if source_text is not None:
            self.source_text = source_text
        if target_text is not None:
            self.target_text = target_text

    @property
    def source_text(self):
        """Gets the source_text of this TermItemForListAITermbaseOutput.  # noqa: E501


        :return: The source_text of this TermItemForListAITermbaseOutput.  # noqa: E501
        :rtype: str
        """
        return self._source_text

    @source_text.setter
    def source_text(self, source_text):
        """Sets the source_text of this TermItemForListAITermbaseOutput.


        :param source_text: The source_text of this TermItemForListAITermbaseOutput.  # noqa: E501
        :type: str
        """

        self._source_text = source_text

    @property
    def target_text(self):
        """Gets the target_text of this TermItemForListAITermbaseOutput.  # noqa: E501


        :return: The target_text of this TermItemForListAITermbaseOutput.  # noqa: E501
        :rtype: str
        """
        return self._target_text

    @target_text.setter
    def target_text(self, target_text):
        """Sets the target_text of this TermItemForListAITermbaseOutput.


        :param target_text: The target_text of this TermItemForListAITermbaseOutput.  # noqa: E501
        :type: str
        """

        self._target_text = target_text

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TermItemForListAITermbaseOutput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TermItemForListAITermbaseOutput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TermItemForListAITermbaseOutput):
            return True

        return self.to_dict() != other.to_dict()
