# coding: utf-8

"""
    veenedge

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class UpdateCloudServerRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'advanced_configuration': 'AdvancedConfigurationForUpdateCloudServerInput',
        'bare_metal_package': 'str',
        'billing_config': 'BillingConfigForUpdateCloudServerInput',
        'cloud_server_desc': 'str',
        'cloud_server_identity': 'str',
        'cloud_server_name': 'str',
        'custom_data': 'CustomDataForUpdateCloudServerInput',
        'disable_vga': 'bool',
        'image_identity': 'str',
        'instance_project': 'str',
        'network_config': 'NetworkConfigForUpdateCloudServerInput',
        'secret_config': 'SecretConfigForUpdateCloudServerInput',
        'storage_config': 'StorageConfigForUpdateCloudServerInput'
    }

    attribute_map = {
        'advanced_configuration': 'advanced_configuration',
        'bare_metal_package': 'bare_metal_package',
        'billing_config': 'billing_config',
        'cloud_server_desc': 'cloud_server_desc',
        'cloud_server_identity': 'cloud_server_identity',
        'cloud_server_name': 'cloud_server_name',
        'custom_data': 'custom_data',
        'disable_vga': 'disable_vga',
        'image_identity': 'image_identity',
        'instance_project': 'instance_project',
        'network_config': 'network_config',
        'secret_config': 'secret_config',
        'storage_config': 'storage_config'
    }

    def __init__(self, advanced_configuration=None, bare_metal_package=None, billing_config=None, cloud_server_desc=None, cloud_server_identity=None, cloud_server_name=None, custom_data=None, disable_vga=None, image_identity=None, instance_project=None, network_config=None, secret_config=None, storage_config=None, _configuration=None):  # noqa: E501
        """UpdateCloudServerRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._advanced_configuration = None
        self._bare_metal_package = None
        self._billing_config = None
        self._cloud_server_desc = None
        self._cloud_server_identity = None
        self._cloud_server_name = None
        self._custom_data = None
        self._disable_vga = None
        self._image_identity = None
        self._instance_project = None
        self._network_config = None
        self._secret_config = None
        self._storage_config = None
        self.discriminator = None

        if advanced_configuration is not None:
            self.advanced_configuration = advanced_configuration
        if bare_metal_package is not None:
            self.bare_metal_package = bare_metal_package
        if billing_config is not None:
            self.billing_config = billing_config
        if cloud_server_desc is not None:
            self.cloud_server_desc = cloud_server_desc
        self.cloud_server_identity = cloud_server_identity
        if cloud_server_name is not None:
            self.cloud_server_name = cloud_server_name
        if custom_data is not None:
            self.custom_data = custom_data
        if disable_vga is not None:
            self.disable_vga = disable_vga
        if image_identity is not None:
            self.image_identity = image_identity
        if instance_project is not None:
            self.instance_project = instance_project
        if network_config is not None:
            self.network_config = network_config
        if secret_config is not None:
            self.secret_config = secret_config
        if storage_config is not None:
            self.storage_config = storage_config

    @property
    def advanced_configuration(self):
        """Gets the advanced_configuration of this UpdateCloudServerRequest.  # noqa: E501


        :return: The advanced_configuration of this UpdateCloudServerRequest.  # noqa: E501
        :rtype: AdvancedConfigurationForUpdateCloudServerInput
        """
        return self._advanced_configuration

    @advanced_configuration.setter
    def advanced_configuration(self, advanced_configuration):
        """Sets the advanced_configuration of this UpdateCloudServerRequest.


        :param advanced_configuration: The advanced_configuration of this UpdateCloudServerRequest.  # noqa: E501
        :type: AdvancedConfigurationForUpdateCloudServerInput
        """

        self._advanced_configuration = advanced_configuration

    @property
    def bare_metal_package(self):
        """Gets the bare_metal_package of this UpdateCloudServerRequest.  # noqa: E501


        :return: The bare_metal_package of this UpdateCloudServerRequest.  # noqa: E501
        :rtype: str
        """
        return self._bare_metal_package

    @bare_metal_package.setter
    def bare_metal_package(self, bare_metal_package):
        """Sets the bare_metal_package of this UpdateCloudServerRequest.


        :param bare_metal_package: The bare_metal_package of this UpdateCloudServerRequest.  # noqa: E501
        :type: str
        """

        self._bare_metal_package = bare_metal_package

    @property
    def billing_config(self):
        """Gets the billing_config of this UpdateCloudServerRequest.  # noqa: E501


        :return: The billing_config of this UpdateCloudServerRequest.  # noqa: E501
        :rtype: BillingConfigForUpdateCloudServerInput
        """
        return self._billing_config

    @billing_config.setter
    def billing_config(self, billing_config):
        """Sets the billing_config of this UpdateCloudServerRequest.


        :param billing_config: The billing_config of this UpdateCloudServerRequest.  # noqa: E501
        :type: BillingConfigForUpdateCloudServerInput
        """

        self._billing_config = billing_config

    @property
    def cloud_server_desc(self):
        """Gets the cloud_server_desc of this UpdateCloudServerRequest.  # noqa: E501


        :return: The cloud_server_desc of this UpdateCloudServerRequest.  # noqa: E501
        :rtype: str
        """
        return self._cloud_server_desc

    @cloud_server_desc.setter
    def cloud_server_desc(self, cloud_server_desc):
        """Sets the cloud_server_desc of this UpdateCloudServerRequest.


        :param cloud_server_desc: The cloud_server_desc of this UpdateCloudServerRequest.  # noqa: E501
        :type: str
        """

        self._cloud_server_desc = cloud_server_desc

    @property
    def cloud_server_identity(self):
        """Gets the cloud_server_identity of this UpdateCloudServerRequest.  # noqa: E501


        :return: The cloud_server_identity of this UpdateCloudServerRequest.  # noqa: E501
        :rtype: str
        """
        return self._cloud_server_identity

    @cloud_server_identity.setter
    def cloud_server_identity(self, cloud_server_identity):
        """Sets the cloud_server_identity of this UpdateCloudServerRequest.


        :param cloud_server_identity: The cloud_server_identity of this UpdateCloudServerRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and cloud_server_identity is None:
            raise ValueError("Invalid value for `cloud_server_identity`, must not be `None`")  # noqa: E501

        self._cloud_server_identity = cloud_server_identity

    @property
    def cloud_server_name(self):
        """Gets the cloud_server_name of this UpdateCloudServerRequest.  # noqa: E501


        :return: The cloud_server_name of this UpdateCloudServerRequest.  # noqa: E501
        :rtype: str
        """
        return self._cloud_server_name

    @cloud_server_name.setter
    def cloud_server_name(self, cloud_server_name):
        """Sets the cloud_server_name of this UpdateCloudServerRequest.


        :param cloud_server_name: The cloud_server_name of this UpdateCloudServerRequest.  # noqa: E501
        :type: str
        """

        self._cloud_server_name = cloud_server_name

    @property
    def custom_data(self):
        """Gets the custom_data of this UpdateCloudServerRequest.  # noqa: E501


        :return: The custom_data of this UpdateCloudServerRequest.  # noqa: E501
        :rtype: CustomDataForUpdateCloudServerInput
        """
        return self._custom_data

    @custom_data.setter
    def custom_data(self, custom_data):
        """Sets the custom_data of this UpdateCloudServerRequest.


        :param custom_data: The custom_data of this UpdateCloudServerRequest.  # noqa: E501
        :type: CustomDataForUpdateCloudServerInput
        """

        self._custom_data = custom_data

    @property
    def disable_vga(self):
        """Gets the disable_vga of this UpdateCloudServerRequest.  # noqa: E501


        :return: The disable_vga of this UpdateCloudServerRequest.  # noqa: E501
        :rtype: bool
        """
        return self._disable_vga

    @disable_vga.setter
    def disable_vga(self, disable_vga):
        """Sets the disable_vga of this UpdateCloudServerRequest.


        :param disable_vga: The disable_vga of this UpdateCloudServerRequest.  # noqa: E501
        :type: bool
        """

        self._disable_vga = disable_vga

    @property
    def image_identity(self):
        """Gets the image_identity of this UpdateCloudServerRequest.  # noqa: E501


        :return: The image_identity of this UpdateCloudServerRequest.  # noqa: E501
        :rtype: str
        """
        return self._image_identity

    @image_identity.setter
    def image_identity(self, image_identity):
        """Sets the image_identity of this UpdateCloudServerRequest.


        :param image_identity: The image_identity of this UpdateCloudServerRequest.  # noqa: E501
        :type: str
        """

        self._image_identity = image_identity

    @property
    def instance_project(self):
        """Gets the instance_project of this UpdateCloudServerRequest.  # noqa: E501


        :return: The instance_project of this UpdateCloudServerRequest.  # noqa: E501
        :rtype: str
        """
        return self._instance_project

    @instance_project.setter
    def instance_project(self, instance_project):
        """Sets the instance_project of this UpdateCloudServerRequest.


        :param instance_project: The instance_project of this UpdateCloudServerRequest.  # noqa: E501
        :type: str
        """

        self._instance_project = instance_project

    @property
    def network_config(self):
        """Gets the network_config of this UpdateCloudServerRequest.  # noqa: E501


        :return: The network_config of this UpdateCloudServerRequest.  # noqa: E501
        :rtype: NetworkConfigForUpdateCloudServerInput
        """
        return self._network_config

    @network_config.setter
    def network_config(self, network_config):
        """Sets the network_config of this UpdateCloudServerRequest.


        :param network_config: The network_config of this UpdateCloudServerRequest.  # noqa: E501
        :type: NetworkConfigForUpdateCloudServerInput
        """

        self._network_config = network_config

    @property
    def secret_config(self):
        """Gets the secret_config of this UpdateCloudServerRequest.  # noqa: E501


        :return: The secret_config of this UpdateCloudServerRequest.  # noqa: E501
        :rtype: SecretConfigForUpdateCloudServerInput
        """
        return self._secret_config

    @secret_config.setter
    def secret_config(self, secret_config):
        """Sets the secret_config of this UpdateCloudServerRequest.


        :param secret_config: The secret_config of this UpdateCloudServerRequest.  # noqa: E501
        :type: SecretConfigForUpdateCloudServerInput
        """

        self._secret_config = secret_config

    @property
    def storage_config(self):
        """Gets the storage_config of this UpdateCloudServerRequest.  # noqa: E501


        :return: The storage_config of this UpdateCloudServerRequest.  # noqa: E501
        :rtype: StorageConfigForUpdateCloudServerInput
        """
        return self._storage_config

    @storage_config.setter
    def storage_config(self, storage_config):
        """Sets the storage_config of this UpdateCloudServerRequest.


        :param storage_config: The storage_config of this UpdateCloudServerRequest.  # noqa: E501
        :type: StorageConfigForUpdateCloudServerInput
        """

        self._storage_config = storage_config

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateCloudServerRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateCloudServerRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UpdateCloudServerRequest):
            return True

        return self.to_dict() != other.to_dict()
