# coding: utf-8

"""
    apig

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class CheckConsumerCredentialExistRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'credential_type': 'str',
        'gateway_id': 'str',
        'hmac_auth_credential': 'HmacAuthCredentialForCheckConsumerCredentialExistInput',
        'key_auth_credential': 'KeyAuthCredentialForCheckConsumerCredentialExistInput',
        'oauth2_credential': 'Oauth2CredentialForCheckConsumerCredentialExistInput'
    }

    attribute_map = {
        'credential_type': 'CredentialType',
        'gateway_id': 'GatewayId',
        'hmac_auth_credential': 'HmacAuthCredential',
        'key_auth_credential': 'KeyAuthCredential',
        'oauth2_credential': 'Oauth2Credential'
    }

    def __init__(self, credential_type=None, gateway_id=None, hmac_auth_credential=None, key_auth_credential=None, oauth2_credential=None, _configuration=None):  # noqa: E501
        """CheckConsumerCredentialExistRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._credential_type = None
        self._gateway_id = None
        self._hmac_auth_credential = None
        self._key_auth_credential = None
        self._oauth2_credential = None
        self.discriminator = None

        self.credential_type = credential_type
        self.gateway_id = gateway_id
        if hmac_auth_credential is not None:
            self.hmac_auth_credential = hmac_auth_credential
        if key_auth_credential is not None:
            self.key_auth_credential = key_auth_credential
        if oauth2_credential is not None:
            self.oauth2_credential = oauth2_credential

    @property
    def credential_type(self):
        """Gets the credential_type of this CheckConsumerCredentialExistRequest.  # noqa: E501


        :return: The credential_type of this CheckConsumerCredentialExistRequest.  # noqa: E501
        :rtype: str
        """
        return self._credential_type

    @credential_type.setter
    def credential_type(self, credential_type):
        """Sets the credential_type of this CheckConsumerCredentialExistRequest.


        :param credential_type: The credential_type of this CheckConsumerCredentialExistRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and credential_type is None:
            raise ValueError("Invalid value for `credential_type`, must not be `None`")  # noqa: E501

        self._credential_type = credential_type

    @property
    def gateway_id(self):
        """Gets the gateway_id of this CheckConsumerCredentialExistRequest.  # noqa: E501


        :return: The gateway_id of this CheckConsumerCredentialExistRequest.  # noqa: E501
        :rtype: str
        """
        return self._gateway_id

    @gateway_id.setter
    def gateway_id(self, gateway_id):
        """Sets the gateway_id of this CheckConsumerCredentialExistRequest.


        :param gateway_id: The gateway_id of this CheckConsumerCredentialExistRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and gateway_id is None:
            raise ValueError("Invalid value for `gateway_id`, must not be `None`")  # noqa: E501

        self._gateway_id = gateway_id

    @property
    def hmac_auth_credential(self):
        """Gets the hmac_auth_credential of this CheckConsumerCredentialExistRequest.  # noqa: E501


        :return: The hmac_auth_credential of this CheckConsumerCredentialExistRequest.  # noqa: E501
        :rtype: HmacAuthCredentialForCheckConsumerCredentialExistInput
        """
        return self._hmac_auth_credential

    @hmac_auth_credential.setter
    def hmac_auth_credential(self, hmac_auth_credential):
        """Sets the hmac_auth_credential of this CheckConsumerCredentialExistRequest.


        :param hmac_auth_credential: The hmac_auth_credential of this CheckConsumerCredentialExistRequest.  # noqa: E501
        :type: HmacAuthCredentialForCheckConsumerCredentialExistInput
        """

        self._hmac_auth_credential = hmac_auth_credential

    @property
    def key_auth_credential(self):
        """Gets the key_auth_credential of this CheckConsumerCredentialExistRequest.  # noqa: E501


        :return: The key_auth_credential of this CheckConsumerCredentialExistRequest.  # noqa: E501
        :rtype: KeyAuthCredentialForCheckConsumerCredentialExistInput
        """
        return self._key_auth_credential

    @key_auth_credential.setter
    def key_auth_credential(self, key_auth_credential):
        """Sets the key_auth_credential of this CheckConsumerCredentialExistRequest.


        :param key_auth_credential: The key_auth_credential of this CheckConsumerCredentialExistRequest.  # noqa: E501
        :type: KeyAuthCredentialForCheckConsumerCredentialExistInput
        """

        self._key_auth_credential = key_auth_credential

    @property
    def oauth2_credential(self):
        """Gets the oauth2_credential of this CheckConsumerCredentialExistRequest.  # noqa: E501


        :return: The oauth2_credential of this CheckConsumerCredentialExistRequest.  # noqa: E501
        :rtype: Oauth2CredentialForCheckConsumerCredentialExistInput
        """
        return self._oauth2_credential

    @oauth2_credential.setter
    def oauth2_credential(self, oauth2_credential):
        """Sets the oauth2_credential of this CheckConsumerCredentialExistRequest.


        :param oauth2_credential: The oauth2_credential of this CheckConsumerCredentialExistRequest.  # noqa: E501
        :type: Oauth2CredentialForCheckConsumerCredentialExistInput
        """

        self._oauth2_credential = oauth2_credential

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CheckConsumerCredentialExistRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CheckConsumerCredentialExistRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CheckConsumerCredentialExistRequest):
            return True

        return self.to_dict() != other.to_dict()
