# coding: utf-8

"""
    vmp

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class VariableForUpdateAlertingRuleTemplateInput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'alias': 'str',
        'default': 'list[str]',
        'include_all': 'bool',
        'multi': 'bool',
        'name': 'str',
        'query': 'str',
        'regex': 'str',
        'type': 'str',
        'values': 'list[str]'
    }

    attribute_map = {
        'alias': 'Alias',
        'default': 'Default',
        'include_all': 'IncludeAll',
        'multi': 'Multi',
        'name': 'Name',
        'query': 'Query',
        'regex': 'Regex',
        'type': 'Type',
        'values': 'Values'
    }

    def __init__(self, alias=None, default=None, include_all=None, multi=None, name=None, query=None, regex=None, type=None, values=None, _configuration=None):  # noqa: E501
        """VariableForUpdateAlertingRuleTemplateInput - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._alias = None
        self._default = None
        self._include_all = None
        self._multi = None
        self._name = None
        self._query = None
        self._regex = None
        self._type = None
        self._values = None
        self.discriminator = None

        if alias is not None:
            self.alias = alias
        if default is not None:
            self.default = default
        if include_all is not None:
            self.include_all = include_all
        if multi is not None:
            self.multi = multi
        if name is not None:
            self.name = name
        if query is not None:
            self.query = query
        if regex is not None:
            self.regex = regex
        if type is not None:
            self.type = type
        if values is not None:
            self.values = values

    @property
    def alias(self):
        """Gets the alias of this VariableForUpdateAlertingRuleTemplateInput.  # noqa: E501


        :return: The alias of this VariableForUpdateAlertingRuleTemplateInput.  # noqa: E501
        :rtype: str
        """
        return self._alias

    @alias.setter
    def alias(self, alias):
        """Sets the alias of this VariableForUpdateAlertingRuleTemplateInput.


        :param alias: The alias of this VariableForUpdateAlertingRuleTemplateInput.  # noqa: E501
        :type: str
        """

        self._alias = alias

    @property
    def default(self):
        """Gets the default of this VariableForUpdateAlertingRuleTemplateInput.  # noqa: E501


        :return: The default of this VariableForUpdateAlertingRuleTemplateInput.  # noqa: E501
        :rtype: list[str]
        """
        return self._default

    @default.setter
    def default(self, default):
        """Sets the default of this VariableForUpdateAlertingRuleTemplateInput.


        :param default: The default of this VariableForUpdateAlertingRuleTemplateInput.  # noqa: E501
        :type: list[str]
        """

        self._default = default

    @property
    def include_all(self):
        """Gets the include_all of this VariableForUpdateAlertingRuleTemplateInput.  # noqa: E501


        :return: The include_all of this VariableForUpdateAlertingRuleTemplateInput.  # noqa: E501
        :rtype: bool
        """
        return self._include_all

    @include_all.setter
    def include_all(self, include_all):
        """Sets the include_all of this VariableForUpdateAlertingRuleTemplateInput.


        :param include_all: The include_all of this VariableForUpdateAlertingRuleTemplateInput.  # noqa: E501
        :type: bool
        """

        self._include_all = include_all

    @property
    def multi(self):
        """Gets the multi of this VariableForUpdateAlertingRuleTemplateInput.  # noqa: E501


        :return: The multi of this VariableForUpdateAlertingRuleTemplateInput.  # noqa: E501
        :rtype: bool
        """
        return self._multi

    @multi.setter
    def multi(self, multi):
        """Sets the multi of this VariableForUpdateAlertingRuleTemplateInput.


        :param multi: The multi of this VariableForUpdateAlertingRuleTemplateInput.  # noqa: E501
        :type: bool
        """

        self._multi = multi

    @property
    def name(self):
        """Gets the name of this VariableForUpdateAlertingRuleTemplateInput.  # noqa: E501


        :return: The name of this VariableForUpdateAlertingRuleTemplateInput.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this VariableForUpdateAlertingRuleTemplateInput.


        :param name: The name of this VariableForUpdateAlertingRuleTemplateInput.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def query(self):
        """Gets the query of this VariableForUpdateAlertingRuleTemplateInput.  # noqa: E501


        :return: The query of this VariableForUpdateAlertingRuleTemplateInput.  # noqa: E501
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query):
        """Sets the query of this VariableForUpdateAlertingRuleTemplateInput.


        :param query: The query of this VariableForUpdateAlertingRuleTemplateInput.  # noqa: E501
        :type: str
        """

        self._query = query

    @property
    def regex(self):
        """Gets the regex of this VariableForUpdateAlertingRuleTemplateInput.  # noqa: E501


        :return: The regex of this VariableForUpdateAlertingRuleTemplateInput.  # noqa: E501
        :rtype: str
        """
        return self._regex

    @regex.setter
    def regex(self, regex):
        """Sets the regex of this VariableForUpdateAlertingRuleTemplateInput.


        :param regex: The regex of this VariableForUpdateAlertingRuleTemplateInput.  # noqa: E501
        :type: str
        """

        self._regex = regex

    @property
    def type(self):
        """Gets the type of this VariableForUpdateAlertingRuleTemplateInput.  # noqa: E501


        :return: The type of this VariableForUpdateAlertingRuleTemplateInput.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this VariableForUpdateAlertingRuleTemplateInput.


        :param type: The type of this VariableForUpdateAlertingRuleTemplateInput.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def values(self):
        """Gets the values of this VariableForUpdateAlertingRuleTemplateInput.  # noqa: E501


        :return: The values of this VariableForUpdateAlertingRuleTemplateInput.  # noqa: E501
        :rtype: list[str]
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this VariableForUpdateAlertingRuleTemplateInput.


        :param values: The values of this VariableForUpdateAlertingRuleTemplateInput.  # noqa: E501
        :type: list[str]
        """

        self._values = values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VariableForUpdateAlertingRuleTemplateInput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VariableForUpdateAlertingRuleTemplateInput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VariableForUpdateAlertingRuleTemplateInput):
            return True

        return self.to_dict() != other.to_dict()
